### ISSUE TITLE
Files missing during `make` step

### ISSUE THREAD

**Issue by olivierlesnicki** [davehorton/drachtio-server#10]
When running the `make` command the following get thrown:

```
Makefile.am: error: required file './AUTHORS' not found
Makefile.am: error: required file './ChangeLog' not found
```

I was able to solve it by manually creating the two files. They should really be part of the repo.

**Comment by davehorton** [comment]
Hi there - was this with the develop branch, or master?  I need to work on the master branch (bringing it up to speed) but suggest you work with develop.  The bootstrap.sh command should have created those files, did it not?

**Comment by olivierlesnicki** [comment]
Should have been the develop branch. I used the scripts detailed in the `README.md`

**Comment by davehorton** [comment]
ok, so you checked out the develop branch and then did this:
```
git clone --depth=50 --branch=develop git://github.com/davehorton/drachtio-server.git && cd drachtio-server
git submodule update --init --recursive
./bootstrap.sh
mkdir build && cd $_
../configure CPPFLAGS='-DNDEBUG'
make
sudo make install
```
If so, and you got those errors, can you tell me which linux distro you were using so I can try to recreate?

**Comment by olivierlesnicki** [comment]
ubuntu 14.04

**Comment by davehorton** [comment]
Believe this is fixed
