### ISSUE TITLE
Maybe wrong proxy behaviour

### ISSUE THREAD

**Issue by Guglio95** [davehorton/drachtio-server#102]
Hi Dave, 
I'm trying out Drachtio's proxy capability but I'm experiencing some issues:
I have an Asterisk PBX + Drachtio running on docker on local server. Drachtio is registered to the provider and is receiving INVITEs;  INVITEs are then proxied to Asterisk which handles the calls.  

Something fun is happening since "200 OK" from my provider is not proxied (to Asterisk) but is sent again to Drachtio's public IP.
Here is what is happening:

> My_Provider —- INVITE ——-> Drachtio 
> Drachtio —— Trying —--—> My_Provider
> Drachtio  ——> INVITE -—-> Asterisk
> Asterisk ——-> TRYING —-> Drachtio
> Asterisk ——> Ringing ——> Drahctio 
> Drachtio ——> Ringing --—> My_Provider
> Asterisk ——> 200 OK ——> Drachtio
> Drachtio ——-> 200 OK -—> My_Provider
> My_Provider —-> ACK ———> Drachtio [[here]](https://gist.github.com/Guglio95/8f0ede708fe2c889f74fb00691f695fb#file-drachtiodebug-txt-L314)
> **Drachtio ——-> ACK ——--> Drachtio** [[here]](https://gist.github.com/Guglio95/8f0ede708fe2c889f74fb00691f695fb#file-drachtiodebug-txt-L332)

The code I'm running is

```js
srf.invite((req, res) => {
    srf.proxyRequest(req, ['asterisk'],
    {
      remainInDialog: true,
      followRedirects: true,
      provisionalTimeout: '3s'
    },
      function(err, results){
        if( err ) { throw err ; }
        console.log(/*JSON.stringify*/(results));
      }
    );
});

```

I'm running drachtio version v0.8.3-4-g8fe175fb0  as:

> drachtio --contact "sip:*;transport=udp --external-ip MY-SERVER-PUBLIC-IP

The container starts with:

>SipTransport::logTransports - udp/127.0.0.1:5060 (sip:*;transport=udp, external-ip: [MY-SERVER-PUBLIC-IP], local-net: ), mtu size: 1300
>SipTransport::logTransports - udp/[MY-DRACHTIO-PRIVATE-DOCKER-IP]:5060 (sip:*;transport=udp, external-ip: [MY-SERVER-PUBLIC-IP], local-net: ), mtu size: 1300

[Here](https://gist.github.com/Guglio95/8f0ede708fe2c889f74fb00691f695fb) I've dumped the app.js debug log and drachtio-server 's one.

**May it be due to [this Route](https://gist.github.com/Guglio95/8f0ede708fe2c889f74fb00691f695fb#file-drachtiodebug-txt-L324) header sent by myProvider?** 

Thank you!

**Comment by davehorton** [comment]
Sorry for the delay in responding..

This seems to me to be a problem with the Voip provider.  drachtio sends a 200 OK to the invite back to the service provider with these Record-Route headers and Contact:
```
Record-Route: <sip:[MY-SERVER-PUBLIC-IP]:5060;lr>
Record-Route: <sip:[VOIP-PROVIDER-IP];lr;ftag=c50f3666.Acc135.B2b30.DbGkDji1MyPBibo37FWEK0087;did=ac8.a54b5b95>
Record-Route: <sip:ITL-RR@62.94.8.72:5060;lr>
Contact: <sip:s@[MY-ASTERISK-PRIVATE-DOCKER-IP]:5060>
```
what I would expect to see in the ACK, therefore would be a SIP URI containing that Contact, and then 1 Route header (the 2 RR headers from the voip provider side should have been removed by the time the final proxy on the provider side sends the ACK).

Instead, we get this:
```
ACK sip:s@[MY-SERVER-PUBLIC-IP]:5060 SIP/2.0
```
That is what leads drachtio  to try to forward the request to itself.

Furthermore, the ACK also has Record-Route headers....these should have been converted to Route headers and should not appear in the ACK.

Can you share with your provider and get their feedback?

**Comment by Guglio95** [comment]
Hi Dave,
I agree with you, this seems a wrong implementation on their side.
I'll try to reach them but for sure they wont fix.

**Comment by davehorton** [comment]
OK, please re-open if they have any feedback
