### ISSUE TITLE
Crash when running in docker

### ISSUE THREAD

**Issue by havfo** [davehorton/drachtio-server#113]
When using docker and the latest: `drachtio/drachtio-server:latest`

I get the following crash immediately upon receipt of the first SIP message after starting the container.

`2020-02-20 12:48:30.638434 processMessageStatelessly - incoming message with call-id 250bd0e165f914a9-1208@127.0.0.1 does not match an existing call leg, processed in thread 140531370149696`
`2020-02-20 12:48:30.638511 No connected clients found to handle incoming options request`
`2020-02-20 12:48:30.638565 processNewRequest - No providers available for OPTIONS`
`Uncaught exception: getrandom`

Environment:
Debian 10 Buster

I'm guessing drachtio attempts to generate a tag or uuid of some sort and crashes.

**Comment by davehorton** [comment]
yes, it uses boot to generate uuids, in this case probably to generate a tag on the To header.

Seems like it might be related to this:

https://github.com/boostorg/uuid/issues/91

I'll have to look into this

**Comment by havfo** [comment]
Tell me if you need some more logs or debugging. I will try to build from source in the meantime.

**Comment by davehorton** [comment]
Yes, please let me know if you have an issue building from source on the latest develop branch.  I don't expect you would, but let me know.

On the docker crash, are you building your own image or using the one at docker.io ?

**Comment by havfo** [comment]
I just tested a source build on the same machine, and it crashed in the same way, with the same config. The build itself went fine.

I used the one on docker.io. I tried to build from the Dockerfile too, but it failed on build:
`Step 3/6 : COPY ./entrypoint.sh /`
`COPY failed: stat /var/lib/docker/tmp/docker-builder062268408/entrypoint.sh: no such file or directory`

**Comment by davehorton** [comment]
OK, this is vanilla Debian 10 as far as you know, right?

**Comment by havfo** [comment]
This is a machine that was dist-upgraded from a vanilla (as far as I know) Debian stretch to Debian buster. Have not tried it on a brand new install of Debian buster.

**Comment by davehorton** [comment]
I built a vanilla Debian 10 on GCP and sent it both a REGISTER and an INVITE (either would cause uuids to get generated) and was not able to recreate the crash.  

Can you let me know what you get when you run these commands on your machine

```
uname -a
Linux buster-testing 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
root@buster-testing:/home/deploy# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by havfo** [comment]
Argh, sorry for wasting your time.

The meta-package `linux-image-amd64` had been lost somewhere along the way. Because of that, I was running an ancient kernel. Upgraded to latest stable and everything seems to run fine.

**Comment by davehorton** [comment]
No worries!

**Comment by havfo** [comment]
By the way, off topic, but is there a community for Drachtio somewhere (IRC, forum...)?

**Comment by davehorton** [comment]
Great question.  No, not at the moment.  I was thinking creating one on slack, just have to find time do the part where I can have a link on the website to let people join without manual intervention (from me!)

**Comment by davehorton** [comment]
Great question.  No, not at the moment.  I was thinking creating one on slack, just have to find time do the part where I can have a link on the website to let people join without manual intervention (from me!)
