### ISSUE TITLE
Record-Route on B2BUA B-leg

### ISSUE THREAD

**Issue by havfo** [davehorton/drachtio-server#115]
Because of [this](https://github.com/davehorton/drachtio-server/blob/master/src/drachtio.cpp#L159), I am unable to add Record-Route on B-leg of B2BUA using `headers : { 'Record-Route' : '<validrecordroute>' }`.

I need to be able to set this as the destination requires this header to be present, and correct based on caller. What are your thoughts on this?

**Comment by havfo** [comment]
How about having a `dangerous` option on the server and/or srf that allows changing dialog headers?

**Comment by davehorton** [comment]
Record-Route is a proxy feature.  It doesn't make any sense to support it in a B2BUA scenario.

Use srf.proxyRequest if you want to proxy a call

**Comment by havfo** [comment]
I agree that it is redundant from a routing perspective, but as far as I am aware, it does not violate RFC 3261.

My problem is that I need to have this header present, and conform to some specifications, but also want to hide my topology beyond drachtio server.

**Comment by havfo** [comment]
It seems I might be able to manage it without adding this header, will try that and reopen if I run into trouble.
