### ISSUE TITLE
Need to set "Contact" header

### ISSUE THREAD

**Issue by simonbooth** [davehorton/drachtio-server#12]
I am creating an app that uses srf.createUasDialog - I cant seems to override the Contact header if I add it to options, it looks correct in the agent send, but on the wire received by the UAC is both the original (wrong) contact and my contact.
Is there a way to do this?

**Comment by davehorton** [comment]
just so I understand, in the response to an INVITE you want to customize the Contact header -- presumably you want to add a user part to the uri and/or add some params, is that correct?  If so, can you give me an example of the uri that you want to construct, so I can try to test and give you a recipe?

**Comment by simonbooth** [comment]
thanks for looking into it - Thats right, the contact header I am trying to set looks like :
Contact: <sip:simon.booth@myfqdn.somewhere>;gruu;opaque=app:conf:focus:id:ABCD1234;isfocus
however the server always inserts its own:
Contact: <sips:server-ip:5061;transport=tls>
so in the end they both appear in the final message that's sent.

**Comment by davehorton** [comment]
Is it possible that you could test this on the latest develop branch - or let me know if you are already doing so?  I think I may have fixed this in a recent checkin.

Just an FYI, if you construct your own Contact header and put in ‘localhost’ for the host part of the uri, the server will substitute the correct IP address in there for you before sending.  Sometimes that is easier than having to construct that part of the uri yourself (though if you want an FQDN in there as in your example below, you may not be interested in that in this case)


On Feb 23, 2017, at 5:59 PM, Simon Booth <notifications@github.com> wrote:

thanks for looking into it - Thats right, the contact header I am trying to set looks like :
Contact: sip:simon.booth@myfqdn.somewhere;gruu;opaque=app:conf:focus🆔ABCD1234;isfocus
however the server always inserts its own:
Contact: sips:server-ip:5061;transport=tls
so in the end they both appear in the final message that's sent.

**Comment by simonbooth** [comment]
I am using the develop branch, latest.

**Comment by davehorton** [comment]
OK, thanks.  I will try to recreate with a simple test app. 
On Feb 24, 2017, at 11:37 AM, Simon Booth <notifications@github.com> wrote:

I am using the develop branch, latest.

**Comment by wcs-machine-user** [comment]
I believe that I have addressed this with the checkin above.  Can you grab the latest from the develop branch and retest?

Just to reiterate, if you want to add a bunch of params to the Contact header, but would like the server to properly insert the host address and port it is listening on, just set the hostport part of your explicit Contact header to 'localhost' and it will be replaced with correct values.
