### ISSUE TITLE
200 Ok with no sdp

### ISSUE THREAD

**Issue by ajay-sabat** [davehorton/drachtio-server#123]
Hi Dave,
We are using Drachtio server with drachtio-siprec-recording-server and Freeswitch. It used to work fine. We are seeing a weird issue that used to work fine before. Drachtio is sending 200 OK response without SDP for the INVITE from Freeswitch. Hence Freeswitch is terminating both the calls by sending BYE for the outbound call and 500 response for the inbound INVITE. I am attaching the log messages from Drachtio. Please check and let me know.
Thanks,
Ajay

[drachtio_siprec_call_failure_200_no_sdp.txt](https://github.com/davehorton/drachtio-server/files/4460372/drachtio_siprec_call_failure_200_no_sdp.txt)

**Comment by davehorton** [comment]
can you open this issue in the repo for the app (drachtio-siprec-recording-server)?

**Comment by ajay-sabat** [comment]
Sure. I will run it again with higher debugging and provide the logs there. Thanks Dave.
