### ISSUE TITLE
can i use microsip or other softphone client to connect drachtio-server ?

### ISSUE THREAD

**Issue by herbiel** [davehorton/drachtio-server#128]
can i use microsip or other softphone client to connect drachtio-server ?

**Comment by davehorton** [comment]
I'm not familiar with microsip (can you send me a link) but you should be able to use any softphone

**Comment by jonzyk** [comment]
I made my first try yesterday with MicroSIP : http://www.microsip.org/ I used the "reject-nice" sample. So far, Drachtio answers 503 to the register request, I got the 486 response.
Sounds good to me.
