### ISSUE TITLE
wss contact not supported and stop to run server

### ISSUE THREAD

**Issue by awadheshkumarconsta** [davehorton/drachtio-server#129]
Hi Team,
I just configured the drachtio server and  installed the tls configuration as mension in doc  after when I add this line 
```
<contacts>
  <contact>sips:*:443;transport=wss</contact>
</contacts>
```

drachtio server is not started.

**Comment by davehorton** [comment]
start it from the command line and dump the output to stdout so we can see the problem:
```
drachtio --stdout
```

**Comment by davehorton** [comment]
I'm assuming you have configured your tls certificates as described [here](https://drachtio.org/docs/drachtio-server#tls)?

**Comment by awadheshkumarconsta** [comment]
Thank you for your reply.
Yes, I have configured the tls certificates as described except this below line attribute 

`<dh-param>xxxxx</dh-param>`

and after adding this line

```
<contacts>
  <contact>sips:*:443;transport=wss</contact>
</contacts>

```

When I restart the drachtio server Ite gives me output like
[https://drive.google.com/file/d/17IfbGo4XaII7VS_H5Qgwdv8zDj16UR1t/view?usp=sharing](url)
and drachtio --stdout is like
[https://drive.google.com/file/d/17IfbGo4XaII7VS_H5Qgwdv8zDj16UR1t/view?usp=sharing](url)

**Comment by davehorton** [comment]
its not finding your <contacts> section, thus is trying to start all protocols, including ws on port 80 which fails.

Can you send me directly your drachtio.conf.xml file at daveh@drachtio.org?

**Comment by awadheshkumarconsta** [comment]
I have sent you my drachtio config file to you.

**Comment by davehorton** [comment]
OK you were actually trying to listen on all of these:
```
        <contacts>
          <contact>sip:*;transport=udp,tcp</contact>
          <contact>sip:*:80;transport=ws</contact>
          <contact>sips:*;transport=tls</contact> 
          <contact>sips:*:443;transport=wss</contact> 
```
remove `<contact>sip:*:80;transport=ws</contact>`, because something else is listening on port 80 -- probably your web server.

As far as wss traffic, you can listen on whatever port you like but since https traffic is usually on 443, I typically move that to something else, like 4433

In general, you probably dont really expect to receive traffic for all those protocols -- remove those you are not really intending to us

**Comment by awadheshkumarconsta** [comment]
Thank you @davehorton , I have installed apache which is using port 80, that's why drachtio server was not running. Once I stop the apache, it starts working. Thanks for your support.

**Comment by davehorton** [comment]
great!
