### ISSUE TITLE
Crash after subscription refreshment

### ISSUE THREAD

**Issue by rhorning** [davehorton/drachtio-server#130]
Hello, @davehorton .

I’ve come across a crash in a Subscribe dialog. It happened in the server (UAS) right after sending the 202 Accepted for a Subscribe refreshing the subscription.

**Flow**
UAC sends SUBSCRIBE
UAS responds with a 202 Accepted
UAS sends a NOTIFY with the current state
UAC responds with a 200 OK
UAC sends SUBSCRIBE to refresh the subscription
UAS responds with a 202 Accepted
UAS crashes

**Analysis**
I’ve run Drachtio Server with GDB to check where it was crashing, and it’s a segmentation fault on **sip-dialog-controller.cpp:931**:
`if(  NULL != strstr( sipResponse->sip_subscription_state->ss_substate, "terminated" ) ) {`

It turns out that _sipResponse->sip_subscription_state_ is null.
Drahctio’s binary was compiled on the **develop** branch in the fix for 126 (958e9190).

**Attachments**
I'm attaching the network trace, core file and Drachtio's log: [subsRefreshCrash.zip](https://github.com/davehorton/drachtio-server/files/4678534/subsRefreshCrash.zip)

Am I missing something?
Thanks in advance!

**Comment by davehorton** [comment]
You are right there is a bug here.  It seems like the code was expecting a Subscription-State header in the 202 response to the SUBSCRIBE, but that is wrong -- that header should only appear in NOTIFYs it seems, per [](https://www.ietf.org/rfc/rfc3265.txt).

What MUST be in the SUBSCRIBE response (per section 3.1.1 of the above) is an Expires header, and the code should be looking at that to determine whether this creates or removes a subscription.

I've made a fix on branch `issue-130`, could you possibly test your app with that?

**Comment by rhorning** [comment]
Hello, Dave.

Thanks for the fast feedback!

2 other crashes happened, in the 202 while refreshing it and in the 202 while terminating the subscription.
I'm attaching both logs because they seem to be crashing in different parts of the code, but they can be related.

**Refresh**
Logs: [refresh.zip](https://github.com/davehorton/drachtio-server/files/4682203/refresh.zip)
The flow is the same as described before.

**Terminate**
Logs: [terminate.zip](https://github.com/davehorton/drachtio-server/files/4682212/terminate.zip)
The flow is very similar. The difference is that the UAC sends the Subscribe with expires 0 and I believe Drachtio detects this and auto 'destroys' the dialog sending the 202:
UAC sends SUBSCRIBE
UAS responds with a 202 Accepted
UAS sends a NOTIFY with the current state
UAC responds with a 200 OK
UAC sends SUBSCRIBE to terminate the subscription (expires 0)
UAS responds with a 202 Accepted (probably an automatic response from Drachtio Server)
UAS crashes

**Comment by davehorton** [comment]
can you show me the stack traces from the core files?  I can't load the actual core file on my side

**Comment by rhorning** [comment]
Sure!

**Refresh**
`Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:298
298     ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x7ffff7fbd780 (LWP 25102))]
(gdb) bt
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:298
#1  0x00005555555b1e28 in strncpy (__len=255, __src=0x0, __dest=0x555555b5b660 "") at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:106
#2  drachtio::UaInvalidData::UaInvalidData (tp=0x555555b5da00, expires=1800, szHost=0x555555b5c12d "127.0.0.14", szUser=0x0, this=0x555555b5b660) at ../src/ua-invalid.hpp:18
#3  __gnu_cxx::new_allocator<drachtio::UaInvalidData>::construct<drachtio::UaInvalidData, char const*&, char const*&, int&, tport_s*&> (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/7/ext/new_allocator.h:136
#4  std::allocator_traits<std::allocator<drachtio::UaInvalidData> >::construct<drachtio::UaInvalidData, char const*&, char const*&, int&, tport_s*&> (__a=..., __p=<optimized out>) at /usr/include/c++/7/bits/alloc_traits.h:475
#5  std::_Sp_counted_ptr_inplace<drachtio::UaInvalidData, std::allocator<drachtio::UaInvalidData>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<char const*&, char const*&, int&, tport_s*&> (__a=..., this=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:526
#6  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<drachtio::UaInvalidData, std::allocator<drachtio::UaInvalidData>, char const*&, char const*&, int&, tport_s*&> (__a=..., this=0x7fffffffca18) at /usr/include/c++/7/bits/shared_ptr_base.h:637
#7  std::__shared_ptr<drachtio::UaInvalidData, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<drachtio::UaInvalidData>, char const*&, char const*&, int&, tport_s*&> (__a=..., __tag=..., this=0x7fffffffca10) at /usr/include/c++/7/bits/shared_ptr_base.h:1295
#8  std::shared_ptr<drachtio::UaInvalidData>::shared_ptr<std::allocator<drachtio::UaInvalidData>, char const*&, char const*&, int&, tport_s*&> (__a=..., __tag=..., this=0x7fffffffca10) at /usr/include/c++/7/bits/shared_ptr.h:344
#9  std::allocate_shared<drachtio::UaInvalidData, std::allocator<drachtio::UaInvalidData>, char const*&, char const*&, int&, tport_s*&> (__a=...) at /usr/include/c++/7/bits/shared_ptr.h:691
#10 std::make_shared<drachtio::UaInvalidData, char const*&, char const*&, int&, tport_s*&> () at /usr/include/c++/7/bits/shared_ptr.h:707
#11 drachtio::DrachtioController::cacheTportForSubscription (this=0x555555b271d0, user=0x0, host=0x555555b5c12d "127.0.0.14", expires=1800, tp=tp@entry=0x555555b5da00) at ../src/controller.cpp:1520
#12 0x0000555555652bc2 in drachtio::SipDialogController::doRespondToSipRequest (this=0x555555b5c940, pData=<optimized out>) at ../src/sip-dialog-controller.cpp:949
#13 0x0000555555653782 in (anonymous namespace)::cloneRespondToSipRequest (p=<optimized out>, msg=<optimized out>, arg=<optimized out>) at ../src/sip-dialog-controller.cpp:46
#14 0x000055555573498a in su_base_port_execute_msgs ()
#15 0x00005555557346c3 in su_base_port_getmsgs ()
#16 0x0000555555734aa2 in su_base_port_run ()
#17 0x00005555556e52e7 in su_port_run ()
#18 0x00005555556e6431 in su_root_run ()
#19 0x00005555555b64dd in drachtio::DrachtioController::run (this=0x555555b271d0) at ../src/controller.cpp:1160
#20 0x00005555555970a9 in main (argc=3, argv=0x7fffffffd6d8) at ../src/main.cpp:47`

**Terminate**
`Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120     ../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
[Current thread is 1 (Thread 0x7ffff7fbd780 (LWP 25404))]
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x00005555555aeb13 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append (__s=0x0, this=0x7fffffffca70) at /usr/include/c++/7/bits/basic_string.h:1256
#2  drachtio::DrachtioController::flushTportForSubscription (this=0x555555b271d0, user=0x0, host=0x555555b5c12d "127.0.0.14") at ../src/controller.cpp:1540
#3  0x0000555555650ccf in drachtio::SipDialogController::doRespondToSipRequest (this=0x555555b5c940, pData=<optimized out>) at ../src/sip-dialog-controller.cpp:952
#4  0x0000555555653782 in (anonymous namespace)::cloneRespondToSipRequest (p=<optimized out>, msg=<optimized out>, arg=<optimized out>) at ../src/sip-dialog-controller.cpp:46
#5  0x000055555573498a in su_base_port_execute_msgs ()
#6  0x00005555557346c3 in su_base_port_getmsgs ()
#7  0x0000555555734aa2 in su_base_port_run ()
#8  0x00005555556e52e7 in su_port_run ()
#9  0x00005555556e6431 in su_root_run ()
#10 0x00005555555b64dd in drachtio::DrachtioController::run (this=0x555555b271d0) at ../src/controller.cpp:1160
#11 0x00005555555970a9 in main (argc=3, argv=0x7fffffffd6d8) at ../src/main.cpp:47
`

Let me know if you need anything else!

**Comment by davehorton** [comment]
Thanks I was not handling the scenario where a SUBSCRIBE with no user in the request-uri.  I checked in a fix on the same branch, could you retest?

**Comment by rhorning** [comment]
The crash is not happening anymore!
But no 'destroy' or 'subscribe' event was emitted in the UAS when receiving a Subscribe with Expires 0. Drachtio just automatically responds 202 Accepted to it.
Should I be expecting for such events? Or any other one that may notify that the susbcription was terminated.

**Comment by davehorton** [comment]
can you send me a log showing the SUBSCRIBE w/ Expires 0 ?

**Comment by rhorning** [comment]
Sure!
Here it is: [drachtio.log](https://github.com/davehorton/drachtio-server/files/4684735/drachtio.log)

**Comment by davehorton** [comment]
ok, yes - the dialog will emit an 'unsubscribe' event with one argument which is the incoming SUBSCRIBE request, e.g.
```
dlg.on('unsubscribe', (req) => console.log('got unsubscribe'):
```

Please check and let me know if that is sufficient for your purpose.

**Comment by rhorning** [comment]
Thanks, Dave! It works for me!

Can this fix be merged to the develop soon?
We're about to compile a new Drachtio Server on the develop branch and it would be great to have this fix.

**Comment by davehorton** [comment]
yes, will merge today

**Comment by davehorton** [comment]
merged
