### ISSUE TITLE
Build server from source failed

### ISSUE THREAD

**Issue by antn9x** [davehorton/drachtio-server#133]
Hi Dave, I have build drachtio from source on Debian 8 and 9, but stuck when compiling source with gcc, can you help to check.
I followed your guide and stuck when run make.
This is my console log:
....
gcc.compile.c++ bin.v2/libs/log/build/gcc-6.3.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/text_file_backend.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.

    "g++"   -fvisibility-inlines-hidden -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden -fno-strict-aliasing -ftemplate-depth-1024 -DBOOST_ALL_NO_LIB=1 -DBOOST_ATOMIC_STATIC_LINK=1 -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_FILESYSTEM_STATIC_LINK=1 -DBOOST_LOG_BUILDING_THE_LIB=1 -DBOOST_LOG_HAS_PTHREAD_MUTEX_ROBUST -DBOOST_LOG_USE_AVX2 -DBOOST_LOG_USE_NATIVE_SYSLOG -DBOOST_LOG_USE_SSSE3 -DBOOST_LOG_WITHOUT_DEBUG_OUTPUT -DBOOST_LOG_WITHOUT_EVENT_LOG -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_DONT_USE_CHRONO=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_LIB=1 -DDATE_TIME_INLINE -DNDEBUG -D_XOPEN_SOURCE=600 -D__STDC_CONSTANT_MACROS  -I"." -I"libs/log/src" -c -o "bin.v2/libs/log/build/gcc-6.3.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/text_file_backend.o" "libs/log/src/text_file_backend.cpp"

...failed gcc.compile.c++ bin.v2/libs/log/build/gcc-6.3.0/release/link-static/threadapi-pthread/threading-multi/visibility-hidden/text_file_backend.o...

**Comment by davehorton** [comment]
I have not seen any problem like that before.  It looks possibility like the cc1plus program was killed for some reason -- is it possible you have very little memory on this server, and the os killed the compile job for that reason?

In general, there are no known issues compiling on debian 9 and I do it all the time

**Comment by alexandremiguelabreu** [comment]
I had a similar problem in CentOS 7. It was a VM with 1 GB and without exchange, I had to increase the RAM to 2 GB for the compilation to work.

**Comment by antn9x** [comment]
Thank for yours quick response. My virtual machine was 512MB, I think that was my problem.
