### ISSUE TITLE
Homer integration using B2BUA

### ISSUE THREAD

**Issue by andgith** [davehorton/drachtio-server#134]
I have been testing the homer integration for Drachtio Server.
Seems to be working well, the only issue I see is that calls made using B2BUA mode are not correctly correlated.

I believe you can set a custom SIP header for Homer to use. Can this be added via the client somewhere or is this a server level thing?

N.B Also I seem to be missing the initial INVITE from the B2BUA call in Homer. The first message I see on the A leg is the 180 Ringing.

Thanks

**Comment by davehorton** [comment]
The client app would need to add the custom header; something like 'X-CID' is what I usually use.
