### ISSUE TITLE
Drachtio-server's log shows an "error enabling tcp keepalive"

### ISSUE THREAD

**Issue by massimo-romano** [davehorton/drachtio-server#14]
Hi Dave,

i'm trying to develop an IVR application in Node.js with Drachtio.
I've a problem with the drachtio-server (either master and dev branches) ; 
when i run this testapp.js on a **Ubuntu 14.04** server :

```
var app = require('drachtio')() ;
var Mrf = require('../') ;
var mrf = new Mrf(app) ;
var Srf = require('drachtio-srf') ;
var srf = new Srf(app) ;
var ms  ;

srf.connect({
  host: '127.0.0.1',
  port: 9022,
  secret: 'cymru',
}, function(hostport) {
  console.log('connected to server listening for SIP messages on ' + hostport) ;
}) ;

mrf.connect({
  address: '127.0.0.1',
  port: 8021,
  secret: 'ClueCon',
  listenPort: 8085
}, function(mediaServer) {
  ms = mediaServer;
  console.log('successfully connected to media server') ;
});

srf.invite( function(req, res) {
  
  // connect caller to an endpoint on the media server
  ms.connectCaller(req, res, function(err, ep, dialog) {
    if( err ) throw err ;

    // set up dialog handlers
    dialog.on('destroy', onCallerHangup.bind(dialog, ep)) ;

    // play some prompts
    ep.play(['ivr/8000/ivr-please_reenter_your_pin.wav',
      'ivr/8000/ivr-please_state_your_name_and_reason_for_calling.wav',
      'ivr/8000/ivr-you_lose.wav'], function(err, results){
        console.log('results: ', results) ;
      }) ;
  }) ; 
}) ;

function onCallerHangup( ep ) {
  // release endpoint
  ep.destroy() ;
}
```

The Drachtio-server's log shows an "error enabling tcp keepalive" :

```
0000003b|2017-May-01 21:59:35.937218| Received connection from client at 127.0.0.1:56774
0000003c|2017-May-01 21:59:35.937374| Client::Client - error enabling tcp keepalive
0000003d|2017-May-01 21:59:35.942937| Client::processAuthentication - validating secret cymru
0000003e|2017-May-01 21:59:35.943664| Client::processAuthentication - secret validated successfully: cymru
```

The testapp.js log shows an **undefined** port and the **drachtio-srf** doesn't seems to work correctly :

```
connected to server listening for SIP messages on undefined
successfully connected to media server
```

Can you help me ?
Do you think this problem is related with the c/c++ library ?

Thanks, 
Massimo

**Comment by davehorton** [comment]
Hi there!  You can ignore the "error enabling tcp keepalive" -- that's a spurious log message I need to remove.

I will check that script and get back to you shortly -- I expect it may be an error of some kind in my example script, not anything on your side

**Comment by davehorton** [comment]
My bad on the example...the callback to Srf#connect has signature (err, hostport), so change this line:
```
srf.connect({
  host: '127.0.0.1',
  port: 9022,
  secret: 'cymru',
}, function(hostport) {
  console.log('connected to server listening for SIP messages on ' + hostport) ;
}) ;
```
to this:
```
srf.connect({
  host: '127.0.0.1',
  port: 9022,
  secret: 'cymru',
}, function(err, hostport) {
  console.log('connected to server listening for SIP messages on ' + hostport) ;
}) ;
```
also, please use the develop branch of drachtio-server.

Let me know if you still have issues after this

**Comment by massimo-romano** [comment]
No, i'm sorry, nothing changed. 
I still have issues after managing the full signature on the develop branch.
The connectCallback doesn't return the SIP address[:port] drachtio server is listening on for incoming SIP messages :

`connected to server listening for SIP messages on undefined
`

I'm a little confused because following the doc and the code :
[http://davehorton.github.io/drachtio-srf/api/Srf.html#~connectCallback](http://davehorton.github.io/drachtio-srf/api/Srf.html#~connectCallback
)

I don't find the callback implementation :
[https://github.com/davehorton/drachtio-srf/blob/master/lib/srf.js#L651](https://github.com/davehorton/drachtio-srf/blob/master/lib/srf.js#L651)
[http://davehorton.github.io/drachtio-srf/api/srf.js.html#line611](http://davehorton.github.io/drachtio-srf/api/srf.js.html#line611)

Maybe, if I'm wrong, the problem could be a misconfiguration of my drachtio.conf.xml ?
In the **contacts** section, i just left the udp,tcp sip tansport.

drachtio.conf.xml

```
<drachtio>
	<admin port="9022" secret="cymru">localhost</admin>  
    <sip>
        <contacts>

            <contact>sip:*;transport=udp,tcp</contact>

        </contacts>
        <spammers action="reject" tcp-action="discard">
            <header name="User-Agent">
                <value>sip-cli</value>
                <value>sipcli</value>
                <value>friendly-scanner</value>
            </header>
            <header name="To">
                <value>sipvicious</value>
            </header>
        </spammers>
    </sip>

    <redis>
        <address>127.0.0.1</address>
    </redis>

    <cdrs>true</cdrs>
            
    <logging>
        <file>
            <name>/tmp/drachtioLogs//drachtio_%Y%m%d_%H%M%S-%N.log</name>
            <archive>/tmp/drachtioLogs/archive</archive>
            <maxSize>5120</maxSize> 
            <minSize>10240</minSize>
            <auto-flush>true</auto-flush>
        </file>

        <sofia-loglevel>9</sofia-loglevel>       
        <loglevel>info</loglevel>
    </logging>
        
</drachtio>
```

**Comment by davehorton** [comment]
Hmm, can you provide the versions of drachtio, drachtio-srf, and drachtio-fsmrf from your app's package.json?

**Comment by massimo-romano** [comment]
```
drachtio-server  0.5.0-6-g58d7e64

Node             v6.10.0
drachtio         1.0.16
drachtio-srf     3.0.11
drachtio-fsmrf   0.102.3
```
I just saw that the latest available version of drachtio is the 1.0.17.
I'm updating this module to see if this is the source of my problem ...

**Comment by davehorton** [comment]
No, I see the problem is that I changed the Srf#connect to not return the hostport information, instead you need to have a connect handler like this:
```
srf.connect({
  host: '127.0.0.1',
  port: 9022,
  secret: 'cymru',
}) 
.on('connect', (err, hostport) => { console.log(`connected to drachtio listening on ${hostport}`) ;})
.on('error', (err) => { console.error(`Error connecting to drachtio at ${err || err.message}`) ; }) ;
```
I've fully updated and tested this example please have a look at it here:

https://github.com/davehorton/drachtio-example-ivr

**Comment by davehorton** [comment]
Let me know if this works for you.  Meanwhile I will update the docs

**Comment by massimo-romano** [comment]
Yes, it works!

```
connected to media server 
connected to drachtio listening on tcp/192.168.0.1:5060,tcp/127.0.0.1:5060,tcp/[::1]:5060,udp/192.168.0.1:5060,udp/127.0.0.1:5060,udp/[::1]:5060
```
Thank you very much for your help.
Your software is becoming a masterpiece : )
