### ISSUE TITLE
request-handler setting of outbound connection not working 

### ISSUE THREAD

**Issue by spointer** [davehorton/drachtio-server#143]
Hi Dave,

I'm trying to change inbound-connection to outbound-connection of srf side.
When i set request-handler section with command-line as follows(i.e, http method POST), i could not get the request body as you mentioned at your drachtio docs.

drachtio --port 4110 --contact "sip:*:4110;transport=udp" --sip-method="INVITE" --http-handler "http://192.168.10.100:4200/route" --http-method "POST" --loglevel debug --sofia-loglevel 9

Any problem on my command-line?
Could you give me any suggestions?

Thanks.

**Comment by davehorton** [comment]
what exactly happens?  Does your handler get a GET request or nothing at all?

**Comment by spointer** [comment]
Handler gets a POST request and query arguments as expected but does not get request body as you mentioned in your docs.

Note: setting http-method="POST" will cause an HTTP POST top be sent to the user-supplied web callback. All of the information supplied below will be provided (e.g. query args) but additionally the body of the request will have a full copy of the incoming SIP request message. This is useful in more complex routing scenarios which may, for instance, depend on examining specific values in the SIP headers of the incoming message.

**Comment by davehorton** [comment]
Is this specifically an issue when you set the handler via command line args?  Can you verify this works when set in the drachtio.conf.xml file ?

**Comment by spointer** [comment]
This is not working when i set in the drachtio.conf.xml file either.

Furthermore, i found all SIP methods(REGISTER, OPTIONS etc.) are received to the request handler when i set sip-method="INVITE" via command-line, but when i set the handler in the conf xml file, only INVITE method is received as expected.

**Comment by davehorton** [comment]
Hmm, this is strange as it works for me (the POST).  Can you get a wireshark trace to verify what exactly is being sent?  Here is what I see in testing on my server when I configure to send POST for INVITEs:

```
POST /?method=INVITE&domain=x.x.x.x&protocol=udp&source_address=x.x.x.x&fromUser=ddddd&toUser=ddddd&uriUser=dddd&contentType=application%2fsdp&uri=sip%3a3322060388%40y.y.y.y.y%3a5060 HTTP/1.1
Host: 127.0.0.1:4000
User-Agent: Drachtio/v0.8.7-rc1-5-g5406d8673
Accept: application/json
Content-Type: text/plain; charset=UTF-8
Content-Length: 1085
Expect: 100-continue

HTTP/1.1 100 Continue

INVITE sip:3322060388@y.y.y..y:5060 SIP/2.0
Via: SIP/2.0/UDP x.x.x.x:5060;branch=z9hG4bK04B054778c3df066bc2;rport=5060
From: "HORTON DAVE    " <sip:5083084809@x.x.x.x>;tag=gK0400d68f
To: <sip:3322060388@y.y.y.y>
Call-ID: 402925461_67097076@x.x.x.x
CSeq: 360764 INVITE
Max-Forwards: 70
Allow: INVITE,ACK,CANCEL,BYE,REGISTER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS,MESSAGE,PUBLISH
Accept: application/sdp, application/isup, application/dtmf, application/dtmf-relay, multipart/mixed
Contact: "HORTON DAVE    " <sip:5083084809@x.x.x.s:5060>
Remote-Party-ID: "HORTON DAVE    " <sip:5083084809@x.x.x.x:5060>;privacy=off
Supported: timer,100rel,precondition
Session-Expires: 1800
Min-SE: 90
Content-Length:   240
Content-Disposition: session; handling=required
Content-Type: application/sdp

v=0
o=Sonus_UAC 609881 60197 IN IP4 x.x.x.x
s=SIP Media Capabilities
c=IN IP4 x.x.x.x
t=0 0
m=audio 60698 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
```

**Comment by spointer** [comment]
I could verify that HTTP post api gets INVITE body with wireshark trace.
But i could not get the right request body from express router what i use for http server.

BTW, when i set sip-method="INVITE" via command-line, request handler gets all SIP methods request but when i set via conf xml file, request handler gets INVITE method as expected. Can you confirm this,  too?

**Comment by davehorton** [comment]
so as far as the POST you are indicating the issue is on your side?

As far as the second issue, could you open a separate issue?

**Comment by davehorton** [comment]
closed due to lack of response
