### ISSUE TITLE
NOTIFY  event not raised on call transfer

### ISSUE THREAD

**Issue by psccodes** [davehorton/drachtio-server#149]
I am using the following code to transfer calls using REFER,

```
dlg.request({
    method: "REFER",
    headers: {
      "Refer-To": `<sip:+${to}@${domain}>`,
      "Referred-By": `<sip:+${from}@${domain}>`,
      Contact: "<sip:localhost>",
    },
  });
  dlg.on("notify", (req, res) => {
    res.send(200);
    this.logger.info(`received NOTIFY with ${req.body}`);
    if (req.get("Subscription-State").match(/terminated/)) {
      this.logger.info("hanging up after transfer completes");
      dlg.destroy();
      ep.destroy();
      this.emit("end");
    }
  });
```

The call gets transferred successfully but the notify event is not received so the call keeps running in the server even after both the parties hang up and it happens in all the cases of transfer. I am attaching complete logs of drachtio-server, I am running the latest v0.8.6, Please let me know if anything else is required.

[drachtio.log](https://github.com/davehorton/drachtio-server/files/5471723/drachtio.log)

**Comment by davehorton** [comment]
I see in your logs you are not getting any NOTIFY messages.  That is because the Contact header looks like this
```
Contact: <sip:localhost>
```
I presume this is coming from the application.  I would have expected the drachtio server to replace 'localhost' with the proper IP address, but it did not.

Could you re-run your test, but this time have loglevel set to debug so I can see the message coming from the app?

**Comment by psccodes** [comment]
After I changed localhost to the server IP it got fixed and is working properly, Here are the logs with loglevel set to debug.

[drachtio.log](https://github.com/davehorton/drachtio-server/files/5473562/drachtio.log)

**Comment by davehorton** [comment]
would you possibly be able to test with the latest release on the develop branch (v0.8.7-rc6) ?

The contact header with 'localhost' should be getting replaced with the appropriate ip of the server, and I am not sure why that is not happening.  It would be good to see if the latest release fixes this or not

**Comment by psccodes** [comment]
I tested with the branch but the issue still exists, here is the log attached with debug loglevel. Please do let me know if anything else is required.

[drachtio.log](https://github.com/davehorton/drachtio-server/files/5477563/drachtio.log)

**Comment by davehorton** [comment]
There is a bug here, but I believe I have a workaround for you.  Just leave the contact header out completely in the headers your app is passing.  The server will add the correct Contact header for you.  This will work with either the earlier build or this build.

Please verify this workaround does in fact work, then let me know if the other issue is still present.

**Comment by psccodes** [comment]
I checked with bot the builds, but I am still not receiving the contact NOTIFY event, the part of the code looked like this

```
 dlg.request({
      method: "REFER",
      headers: {
         "Refer-To": `<sip:+${to}@${domain}>`,
         "Referred-By": `<sip:+${from}@${domain}>`,
        // Contact: "<sip:localhost>",
      },
    });

```

I am attaching the debug logs of both the builds,

[drachtio87-rc2.log](https://github.com/davehorton/drachtio-server/files/5480582/drachtio87-rc2.log)
[drachtio86.log](https://github.com/davehorton/drachtio-server/files/5480583/drachtio86.log)

**Comment by davehorton** [comment]
I see - it is putting the private IP address in the Contact header rather than the public contact header.  If I create a new branch to test a fix, would you be able to build and test it?

**Comment by psccodes** [comment]
yes I will be happy to do it.

**Comment by davehorton** [comment]
can you test the branch named 'refer-fixes'?  There is no need for you to supply the Contact header, the server should put on the proper one now

**Comment by psccodes** [comment]
Alright will do that.

**Comment by psccodes** [comment]
Hello Dave, I built and tested and the fix looks perfectly fine, I removed the contact header and it worked as expected, thanks for the fix.

**Comment by davehorton** [comment]
merged into develop branch

**Comment by psccodes** [comment]
Thanks, closing the issue
