### ISSUE TITLE
Possible error on Content-Type Header detection

### ISSUE THREAD

**Issue by daimoc** [davehorton/drachtio-server#15]
I'm trying to send DTMF in SIP INFO request and I always got a missing content-type error  :

> SipDialogController::doSendRequestInsideDialog - Error: missing content-type
 
In my Nodejs code I put a content-type header but it's not seen in sever part.

> app.request({
>                 method: 'INFO',
>                 stackDialogId: dialog,
> 			headers: {
> 			  'User-Agent': 'dracht.io',
> 			  'Content-Type': ' application/dtmf-relay'
> 			},
> 			body: messageBody
>               }, function(err, req){}

Looking at  SipDialogController::doSendRequestInsideDialog line 177 I found  that !searchForHeader( tags, siptag_content_type, contentType )  is using siptag_content_type and not siptag_content_type_str. 
It may be the reason of issue in content-type header detection.

**Comment by davehorton** [comment]
Hi there!  Thanks for point this out.  It looks like you are testing with the master branch -- it's my fault but that branch is way behind.  Can you switch to the develop branch, where I believe I fixed this issue?  Let me know if it is still an issue there. (separately, I'll work on merging develop into master, but please just use the develop branch going forward)

**Comment by daimoc** [comment]
Ok thanks Dave.
I switch to develop branch and it works. I can send my DTMF with SIP INFO request to my Asterisk PABX from my WebRTC gateway.
