### ISSUE TITLE
Drachtio exits immidiately on startup

### ISSUE THREAD

**Issue by lee-orr** [davehorton/drachtio-server#21]
I've compiled drachtio-server, and tried to run it. I know that it runs because it creates errors when it doesn't have a config file. However - the moment I correct the config file it just starts and exits. It doesn't send any output to the console.
Do you have an idea of how to solve this?

**Comment by davehorton** [comment]
which branch are you running on?  If you are using the default config file, a log file should be written to `/var/log/drachtio/drachtio/log`.  Do you see a log file there?  If so, it should tell you why it is stopping.

A couple of other things to try:

1) First, run `drachtio --version` to see what version you are running, and post it here

2) Depending on which branch, you  can either add a <console/> element to the log section of the config file to get logging at the console, or run with these parameters:

`drachtio --contact "sip:*;transport=udp" --loglevel debug`

to override the config file.

If possible, can you try to recreate on the cluster-experimental branch?  I am doing a lot of work that will be integrated into the develop branch shortly...

**Comment by davehorton** [comment]
Also if you just want to get up and running and avoid the build step you can always use the docker image `drachtio/drachtio-server:latest`

**Comment by lee-orr** [comment]
I was using master, version 0.5.0-122-g3a17efc. For some reason no log was created.
Running it with the --contact parameter worked for some reason... So while I'll take a look at the cluster-experimental branch, it is working now.

Thanks for the quick response!

**Comment by davehorton** [comment]
OK, if you can please change to using the develop or cluster-experimental branches, those are the most active.  I need to eventually merge this stuff into master but its a bit behind right now.
