### ISSUE TITLE
Building from source on Darwin/Mac

### ISSUE THREAD

**Issue by andrewvmail** [davehorton/drachtio-server#30]
Instructions wasn't smooth sailing for me trying to build on a Mac (maybe its my computer but for anyone running into the same issue):
- had to remove openssl that ships with the os by disabling System Integrity Protection and deleting the binary. remember to turn it back on.
- installed openssl through brew
- make sure /usr/local/Cellar/openssl only have one openssl incase of old install through brew. didnt build until i got only the latest (OpenSSL 1.0.2o  27 Mar 2018)
- I installed```brew curl --with-openssl```
- i was using boost that got installed through brew but that didn't come with -lboost_thread has -lboost-thread_mt instead. Did the solution here https://discourse.brew.sh/t/could-not-link-to-boost/2125/4 but then craps out on re_detail_106300 (some regex method i think compatibility with the brew version)
- uninstall boost from brew and used the one in deps 
- finally compiled the binary
- ran into a bunch of these when trying to run the compiled drachtio binary
```
dyld: Library not loaded: libboost_log.dylib
  Referenced from: /usr/local/bin/drachtio
  Reason: image not found
```
- from the deps/boost directory i symlink those dylib with ``` find bin.v2/libs | grep .dylib | awk '{system("ln -s $PWD/" $1 " /usr/local/lib")}'``` assumig pwd is project/deps
- then all good just need to create /etc/drachtio.conf.xml 
- have to run drachtio using sudo because of /var/log/drachtio permission
- Yay working!!

Could have just run in docker but on the mac docker doesn't run natively, instead in a vm docker-machine (virtual box) with its own network subnet so the networking is behind another layer. used socat to proxy to the docker-machine it works but just incase best to run in host

👍

**Comment by davehorton** [comment]
Yeah, sorry it was such a pain.  I got it working on my mac a while back but have basically assumed standard linux distributions would be used for production so I never quite worked out all the kinks to make the build less painful....so impressed you worked through all of that!  I will try to capture some of that and factor it back into a better build script if and when I get time.  Thanks again

**Comment by andrewvmail** [comment]
Hi Dave, 

Yeah I think I recall 2 years back I got it building on the Mac. In production I'll be using the docker image you have so for the most part its actually not so bad I think just leaving this issue is good enough. Its cool though now I can spin up Drachtio bare without the overhead of virtualhost. 

Thanks for this awesome software!!

**Comment by andrewvmail** [comment]
Linking to https://github.com/davehorton/drachtio-server/pull/34

**Comment by andrewvmail** [comment]
#36 should take care of this
