### ISSUE TITLE
Handling simultaneous SIP requests

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-server#31]
Hi,

One issue I see from one of the clients we are testing is that after REGISTER, a SUBSCRIBE and PUBLISH are sent as separate transactions, but at relatively the same time. It appears as though drachtio-server (latest develop branch) seems to lose state. For example, it may respond properly tot he PUBLISH. In our code using drachtio-srf, we send a NOTIFY in response to the SUBSCRIBE (to reg events in this case). That NOTIFY ends up going out without a "To tag", with the wrong (a new?) "From tag", but with the correct Call-ID (of the SUBSCRIBE dialog).

It looks like in this case, SUBSCRIBE is received by drachtio, then a PUBLISH, PUBLISH is responded with 200 OK, then the SUBSCRIBE gets 200 OK, then the NOTIFY goes out with the incorrect information.

Sometimes it works, perhaps some minor timing changes cause different call flow. If we disable PUBLISH, it works fine as well. We are also looking to make the SUBSCRIBE/PUBLISH flow sequential, but, I am not sure if that is limited by standards for non-INVITE requests.

I am working on some logs and a packet capture to send to you.

Thanks

**Comment by davehorton** [comment]
I will try to recreate.  So the sequence is

client         drachtio
———> REGISTER 
<—— 20 OK
————> SUBSCRIBE
—————> PUBLISH
<———— 202 (SUBSCRIBE)
<—————200 (PUBLISH)
<—————NOTIFY

Is that right?

On May 24, 2018, at 8:15 PM, James <notifications@github.com> wrote:

Hi,

One issue I see from one of the clients we are testing is that after REGISTER, a SUBSCRIBE and PUBLISH are sent as separate transactions, but at relatively the same time. It appears as though drachtio-server (latest develop branch) seems to lose state. For example, it may respond properly tot he PUBLISH. In our code using drachtio-srf, we send a NOTIFY in response to the SUBSCRIBE (to reg events in this case). That NOTIFY ends up going out without a "To tag", with the wrong (a new?) "From tag", but with the correct Call-ID (of the SUBSCRIBE dialog).

It looks like in this case, SUBSCRIBE is received by drachtio, then a PUBLISH, PUBLISH is responded with 200 OK, then the SUBSCRIBE gets 200 OK, then the NOTIFY goes out with the incorrect information.

Sometimes it works, perhaps some minor timing changes cause different call flow. If we disable PUBLISH, it works fine as well. We are also looking to make the SUBSCRIBE/PUBLISH flow sequential, but, I am not sure if that is limited by standards for non-INVITE requests.

I am working on some logs and a packet capture to send to you.

Thanks

**Comment by JimG777** [comment]
Just a minor modification, PUBLISH is answered first:

client         drachtio
———> REGISTER
<—— 200 OK
————> SUBSCRIBE (event: reg)
—————> PUBLISH
<————— 200 (PUBLISH)
<———— 200 (SUBSCRIBE)
<———— NOTIFY (event: reg)

**Comment by JimG777** [comment]
Yes, agreed that PUBLISH and SUBSCRIBE are separate, at least PUBLISH is not part of dialog started by SUBSCRIBE. Both have different From tag and Call-ID when sent from our client.

What is mostly interesting is that 4 out 5 tests show the problem, but it sometimes works. That 1 time out of 5 the NOTIFY comes with the correct Call-ID and From tag, with the new To tag from. Possibly a timing or concurrency issue?

**Comment by JimG777** [comment]
Here are packet dumps of a good example and bad showing the SIP headers, in case it helps build a test vector.

[sub_pub_good.txt](https://github.com/davehorton/drachtio-server/files/2040227/sub_pub_good.txt)
[sub_pub_bad.txt](https://github.com/davehorton/drachtio-server/files/2040229/sub_pub_bad.txt)

**Comment by davehorton** [comment]
I'm having trouble recreating, and I think I need more insight into what your code looks like.

I tried recreating by using `srf.createUAC` when receiving the SUBSCRIBE, then on the created dialog calling `dlg.request({method: 'NOTIFY'..`.  However, I cannot recreate the race condition, and also you must be doing something different since `srf.createUAC` would generate a 202 response to the SUBSCRIBE whereas you are generating a 200 in your trace.

can you comment on how I can make my simple test case look more like yours?  Here is what I am testing (which seems to not hit this race condition)

```
    // respond to publish and register immediately
    this.srf.register((req, res) => {
      console.log('sending 200 OK to register');
      res.send(200);
    });
    this.srf.publish((req, res) => {
      console.log('sending 200 OK to publish');
      res.send(200);
    });

    // slight delay in responding to subscribe
    this.srf.subscribe((req, res) => {
      console.log('got SUBSCRIBE');
      setTimeout(() => {
        console.log('sending 200 OK to SUBSCRIBE');
        this.srf.createUAS(req, res)
          .then((dlg) => {
            console.log('sending NOTIFY');
            return dlg.request({
              method: 'NOTIFY',
              headers: {
                'Subscription-State': 'active',
                'Event': req.get('Event')
              }
            });
          })
          .catch((err) => console.log(`Error responding to SUBSCRIBE: ${err}`));
      }, 200);
```
I use the above test app, and then send the following sequence from a sipp uac:
--> REGISTER
<-- 200 OK
--> SUBSCRIBE
--> PUBLISH
<-- 200 OK (PUBLISH)
<-- 202 Accepted (SUBSCRIBE)
<-- NOTIFY

**Comment by JimG777** [comment]
We aren't using createUAS. Also, I think we are more aligned to RFC 6665 in which 202 response for SUBSCRIBE is deprecated, but nonetheless the 200/202 are supposed to be treated the same. But if you are saying the drachtio-* will behave differently if 202 is sent, then we can try that.

Also, just to clarify, the PUBLISH and SUBSCRIBE are separate. PUBLISH from the client is for 'presence' and the SUBSCRIBE is for 'reg' (events).

Here is the code for pub/sub we are using, with some field processing and user management parts removed.

```
srf.publish((req, res) => {
    var sipEtag = 'some_generated_value';

    res.send(200, {
        headers: {
            'Expires': req.msg.headers.expires,
            'SIP-ETag': sipEtag
        }
    });
});

srf.subscribe((req, res) => {
    // Send a 200 response to the subscribe.
    res.send(200, {
        headers: {
            expires: 3600
        }
    });

    // Send NOTIFY using srf.request()
});
```

I think, perhaps we should be using createUAS and dlg.request to send the NOTIFY as per your example? We've just been doing it manually.

**Comment by davehorton** [comment]
BTW, it is fine doing things like that, you do not necessarily need to change to use `dlg.request`.  Totally up to you.  As long as you include the `Call-ID` in the headers of the request, the server should set things up properly

**Comment by JimG777** [comment]
In your example, one more curly bracket is needed after the headers block since the callback is the next parameter after the options.

This seems to help resolve the issue, but there are some new problems. If I send 5 users through the reg/pub/sub process:

- Some users get registered and the sub/pub/notify works, sometimes only one.
- Sometimes "Error: invalid message from server, did not start with length#:"
- Sometimes "Error: unexpected message with type: undefined"

It is always thrown from here:
drachtio/lib/wire-protocol.js:280

at WireProtocol._onData (drachtio/lib/wire-protocol.js:244:21)

or

at DrachtioAgent._onMsg (drachtio/lib/drachtio-agent.js:675:15)

I will look over my code to find other causes.

**Comment by davehorton** [comment]
Hmm, 'invalid message from server, did not start with length’ is a pretty low level error, it means that somehow the message between server and client was formatted incorrectly or was corrupted somehow.  I’m not totally sure what it points to.

The best way for me to help troubleshoot this is if you can set the drachtio server loglevel to debug and capture a full log from drachtio server for this sequence


On May 29, 2018, at 5:19 PM, James <notifications@github.com> wrote:

In your example, one more curly bracket is needed after the headers block since the callback is the next parameter after the options.

This seems to help resolve the issue, but there are some new problems. If I send 5 users through the reg/pub/sub process:

Some users get registered and the sub/pub/notify works, sometimes only one.
Sometimes "Error: invalid message from server, did not start with length#:"
Sometimes "Error: unexpected message with type: undefined"
It is always thrown from here:
drachtio/lib/wire-protocol.js:280

at WireProtocol._onData (drachtio/lib/wire-protocol.js:244:21)

or

at DrachtioAgent._onMsg (drachtio/lib/drachtio-agent.js:675:15)

I will look over my code to find other causes.

**Comment by JimG777** [comment]
Log file is uploaded. Here, user 0 (14085550000) causes the problem immediately:

--> REGISTER
<-- 401/200 OK
--> SUBSCRIBE
--> PUBLISH
PROBLEM

Then, later the other clients get handled after retries or server restarts.

[problem.txt](https://github.com/davehorton/drachtio-server/files/2051580/problem.txt)

[log.txt](https://github.com/davehorton/drachtio-server/files/2051549/log.txt)

**Comment by davehorton** [comment]
could you re-run with DEBUG=drachtio:* on the client side, and include that log?

**Comment by davehorton** [comment]
also in the logs, pidf xml content in the PUBLISH that is coming through looks like it has some unprintable characters in the 'entity' attribute of the 'presence' tag.  What is that?  I am thinking that it is blowing up on the PUBLISH message for some reason, and if the content is not utf8 encoding that may be the reason.

**Comment by davehorton** [comment]
can you confirm also you are running drachtio-srf v 4.2.17 ?  That is the latest, and includes some fixes for proper handling of utf8 strings....I had actually ran into issues having to do with content that included emojis, which made me realize that I was not handling utf8 correctly in prior releases.

**Comment by JimG777** [comment]
Thank you very much for taking a detailed look!

[app_log.txt](https://github.com/davehorton/drachtio-server/files/2051717/app_log.txt)
[log.txt](https://github.com/davehorton/drachtio-server/files/2051718/log.txt)

**Comment by davehorton** [comment]
I'm pretty sure it has something to do with those unprintable characters in the pidf payload, so I would be interested to know what they are, and what the encoding is.  If its utf8 encoding, I *should* be handling it, but maybe I have a bug.

Perhaps we can try to determine whether that is in fact the problem by having you send a PUBLISH without those special characters (simple ascii encoding) to see if the problem does then *not* occur?

**Comment by JimG777** [comment]
Yes, that entity field looks corrupt, even some Wireshark traces are broken because of it. It should be a sip uri. I am checking client code and will either send proper information or none for testing. This certainly looks like our problem. I will test as soon as we have a fix and let you know. Really sorry if this is causing some of the issues. But I think the advice for sending the NOTIFY in the callback was right on. Thanks.

**Comment by davehorton** [comment]
OK, let me know.  no need to be sorry -- all good.  I should probably burp out some more useful log/diagnostic to help pinpoint these types of issues.

**Comment by JimG777** [comment]
Using a PUBLISH body with valid characters, operation was as expected without issue.
.
