### ISSUE TITLE
NAT handling

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-server#38]
Up till now, I have done lots of testing with drachtio-server running in a Docker network along with my other services. External clients could come in and access the server, but it was all enclosed by a private network.

Now I am trying to deploy the Docker setup to AWS. However, when I run drachtio-server in a Docker network on an AWS EC2 instance, I can't getting NATing working correctly. The drachtio-server can't reach my clients. I even tries running drachtio-server directly on an AWS EC2 instance, but it has the same results. The log below is this case without Docker.

[drachtio.txt](https://github.com/davehorton/drachtio-server/files/2129447/drachtio.txt)

In this example, my client REGISTERs, sends a SUBSCRIBE, and sends a PUBLISH. We get the 200 OK responses back for both of those. However, the NOTIFY we send from the Node.js/srf side doesn't reach the client. This is after the fix from before where we now send the NOTIFY after the 200 OK is successfully sent (it works well in the private network scenario).

In the log, 5.5.5.5 is the public IP from my office and 10.11.33.* is the private IP range. 222.222.222.222 is the public IP of the AWS EC2 instance and 10.0.3.* is the private IP range there.

When I send the NOTIFY with the drachtio-srf object, I am using the received and rport parameters from the via[0] line (5.5.5.5:5070). But from the logs it looks like drachtio-server is trying to send to the private IP of my office network.

**Comment by davehorton** [comment]
Hi there, yes till now I have not dealt with any NAT scenarios.  Let me look into this.  I'll probably create a branch to work on, and hope to have something for you to test this week

**Comment by davehorton** [comment]
Could you retry your scenario with the docker image `davehorton/drachtio-server:edge` ?  This is not the complete fix that I want to do, but I want to verify if possible whether the change I made sorts out your scenario.

**Comment by davehorton** [comment]
alternatively, build the latest on the 'nat-handling' branch and test with that.  If you are able to test both the nat'ed and non-nat'ed scenarios, that would be helpful

**Comment by JimG777** [comment]
I have done the tests. Please see the log files:

[bad_edge_nat.txt](https://github.com/davehorton/drachtio-server/files/2130155/bad_edge_nat.txt)
[good_edge_local.txt](https://github.com/davehorton/drachtio-server/files/2130156/good_edge_local.txt)
[good_local.txt](https://github.com/davehorton/drachtio-server/files/2130157/good_local.txt)

good_local.txt is the local network testing from before for reference.
good_edge_local.txt is the local network testing with the edge docker instance.
bad_edge_nat.txt is the nat testing with drachtio running in a docker network on an AWS EC2 instance.

I confirmed that I am pulling the edge branch docker (v0.7.3-rc1-1-g**b384a4b**). However, that is not your latest commit, since they are failing automatic github builds.

**Comment by davehorton** [comment]
Its strange, in that there are log messages that I put in the code which should be appearing in your log (the bad log) but are not.  I just made one minor logging change, and the docker image (edge label) should finish building in a bit -- could you re-run the nat test with that, so I can see those log messages?

(You can ignore the build failures for now -- there are some post-build tests which for some reason are failing on travis which pass locally that I am looking into)

**Comment by JimG777** [comment]
Ok, I have mixed results but seems in a good direction... For some reason, I guess the Docker drachtio-server:edge tag won't pull from the latest commit, just the latest successful one. So I manually built the images in Docker from the latest commit (v0.7.3-rc1-4-gf942515).

[bad_edge_local.txt](https://github.com/davehorton/drachtio-server/files/2130253/bad_edge_local.txt)
[good_edge_nat.txt](https://github.com/davehorton/drachtio-server/files/2130254/good_edge_nat.txt)

"bad_edge_local.txt" -> When I tested locally, my client didn't get a 200 OK for the SUBSCRIBE. So couldn't move on from there.

"good_edge_nat.txt" -> When I tried from the AWS side (again, in an AWS EC2 instance running in a Docker container), the NOTIFY was successful! It works there.

**Comment by davehorton** [comment]
yes, it looked like it crashed in the bad-local scenario when attempting to send the 200 OK to the SUBSCRIBE.  I'm sure this is related to my changes.  Any changes you can get a stack trace?

**Comment by davehorton** [comment]
I think I figured out the issue - it looks like it was crashing on a new log statement I put in, in the non-nat case.  I've checked in a fix, when it finishes building can you retest both scenarios?

**Comment by JimG777** [comment]
Sure! It was taking a while to get gdb in to the Docker container. Will leave it in for now...

**Comment by JimG777** [comment]
Alright, I have retested and attached the current logs. Both local and remote/nat work, for the NOTIFY case. I will also start to test session establishment (INVITE) between remote clients (proxied via srf). Do you think your fix will help them, or should I await further adjustments? They weren't working before, with similar behavior to the NOTIFY.

[good_edge_local_fix.txt](https://github.com/davehorton/drachtio-server/files/2130314/good_edge_local_fix.txt)
[good_edge_nat_fix.txt](https://github.com/davehorton/drachtio-server/files/2130315/good_edge_nat_fix.txt)

**Comment by davehorton** [comment]
It would probably help the INVITE scenario if you app is a B2B but possibly not if you are a proxy.  Please do retest and attach your logs if it doesn't work so I can have a look

**Comment by JimG777** [comment]
Here is the INVITE case. User 8 registers, then user 9. User 9 attempts to send an INVITE to user 8. It never leaves the server.

[rcs_invite_nat.txt](https://github.com/davehorton/drachtio-server/files/2131756/rcs_invite_nat.txt)

It is a proxy using the srf object. Thanks.

**Comment by davehorton** [comment]
Interesting, the problem there is different.  We try to send the invite via udp, but the sip stack complains the message is too large, and then tries tcp, which won't work to that client:

`nta.c:8463 outgoing_try_tcp_instead() nta: INVITE (1) too large for UDP, trying TCP`

I will probably have to make a change to fix this, but could you retest that same scenario with this as the destination: 

`sip:5.5.5.5:5070;transport=UDP`

i.e., lets just see what happens if you explicitly request UDP.

**Comment by JimG777** [comment]
When we set transport=UDP, we don't see any change in behavior. The logs are:

[invite_transport_udp.txt](https://github.com/davehorton/drachtio-server/files/2134732/invite_transport_udp.txt)

I also tried forcing tcp from the client side by setting mtu size to something very low. This actually works, but the drachtio server can't send ACK because it tries to do so over UDP. For this I removed the "transport=UDP" setting. The logs are:

[invite_force_tcp.txt](https://github.com/davehorton/drachtio-server/files/2134736/invite_force_tcp.txt)

I tired running drachtio-server with only tcp support (sip:*:15060;transport=tcp), but it crashed when trying to find a candidate for for the protocol (you can see at line 1039 where it starts again). Sorry, I don't have a stack trace. The logs are:

[invite_tcp_only.txt](https://github.com/davehorton/drachtio-server/files/2134745/invite_tcp_only.txt)

I notice in our client that we aren't setting "transport=tcp" in our contact header or via. We are looking to make sure this is done. Is drachtio-server looking for it?

**Comment by davehorton** [comment]
OK, I appreciate you running these tests.  At this point, with your logs I think I have enough data to recreate something in my environment.  I'm going to first make a build that removes (or increases) the limit on UDP message size that is being triggered in your initial case, as I have run into this as well and I think it is unnecessarily low for most cases.

**Comment by davehorton** [comment]
I just made a commit to increase the mtu over udp to 4096.  This is not the fix but I would like to see what your results are with this build if you have a chance ... not forcing it to udp or tcp, just the original scenario.  I'll probably end up making this configurable, but I would like to push through this initial issue to see what lies on the other side.  Its building now on docker...

**Comment by JimG777** [comment]
Quick question: When I remove my Docker drachtio/drachtio-server:edge image and pull it again, it is still on version b384a4b (from 4 days ago), not the latest commit. Is there some trick to get it to pull from the latest commit? Otherwise, I need to rebuild the image in AWS, which takes time.

**Comment by davehorton** [comment]
Sorry I think that was my problem...I forgot to update the Dockerfile on the branch to refer to the branch, so I think it was kicking off the build for the 'develop' branch.  Just committed that change, building now.

**Comment by JimG777** [comment]
Ok great! I will give it try.

**Comment by davehorton** [comment]
You should see some extra logging at startup along the lines of this:
`reset mtu size to: 4096 transport: udp/127.0.0.1:5060`

**Comment by JimG777** [comment]
In these logs, I tried a few sessions to see how things work. The first session had some issue, but it may be an MO issue. At least, you can see the ACK handling for a subsequent session around line 4280. The transport it finds should be 7.7.7.7:30967 I think...

[rcs_test_udp.txt](https://github.com/davehorton/drachtio-server/files/2139120/rcs_test_udp.txt)

**Comment by davehorton** [comment]
So here is what I see in that log:

- we get the INVITE from the client
- your app proxies it on, without adding a record-route header
- we get the 200 OK from the far end, and pass that back to the caller
- now, since you did not add a record route header, it is up to the calling device to send the ACK directly to the far end
- since we see retransmits of the 200 OK from the far end, I assume your calling device could not send the ACK to the address of the Contact header in the 200 OK, which is
`sip:+14085550007@172.16.133.195:15000;transport=UDP`

so if you want or expect the ACK to go through the drachtio server then you would add a property to the proxyRequest call `opts.remainInDialog` (alias `opts.recordRoute`)

**Comment by JimG777** [comment]
I am already setting that option:

```
srf.proxyRequest(req, dest, {
    forking: 'sequential',
    remainInDialog: true,
    provisionalTimeout: '15s',
    finalTimeout: '30s',
    followRedirects: false
}, (err, results) => {
...
});
```

**Comment by davehorton** [comment]
Ah, right I missed that, sorry.

So then the question is, why is the sending client not sending the ACK to `sip:172.25.0.3:15060`, per the record-route header?  Where, in fact, is it sending it?

Also, why is there a Route header in the initial INVITE?

**Comment by JimG777** [comment]
Hi, we fixed a few issues on the client side such as transport was always set to UDP in the contact even though it was actually TCP and our TCP port was incorrect (which led to some other issues). Also, I have run a local modification of the drachtio-server to set the UDP mtu to 100 so that it favors TCP only. This would be better for us. I will send some fresh logs shortly. We still see the ACK problem, it just doesn't go out.

Do you think the Route header is a problem? I believe it was set as an outbound proxy, but we can disable it.

**Comment by davehorton** [comment]
The Route header is not necessarily a problem for me...I am just proxying it on.  I'm not used to seeing it on a new INVITE, and not sure whether it is valid there.  I guess the main point is that if you are expecting me to strip it, I am not.  Perhaps the presence of that Route header is a problem for the client, and the reason it is not sending the ACK out?

I'm not sure whether the results of dropping the mtu down to 100 are going to be great for you....it will cause tcp top be used for every outbound message.  If you really just want to use tcp only, why dont you just start the drachtio server with only a tcp endpoint (/contact)?

**Comment by JimG777** [comment]
Good question, I think the issues we had from our side were forcing some UDP, so it never worked. But now I will test the scenario again with TCP only and post the log here. Thanks.

**Comment by JimG777** [comment]
[tcp_log_noroute.txt](https://github.com/davehorton/drachtio-server/files/2146770/tcp_log_noroute.txt)
[tcp_log_route.txt](https://github.com/davehorton/drachtio-server/files/2146771/tcp_log_route.txt)

These two logs show the same scenario with route header in and not in the Invite. So I think you can focus on the noroute version. Either way, the behavior is the same.

Here, I have set the server to use the edge of the nat-handling branch (no changes from me), but I have set the contact for tcp only. It doesn't get very far. The INVITE comes, 100 Trying is sent, but it is not forwarded/proxied. I can see the log entry on line 796 where it is searching for "udp/sip:5.5.5.5:15000". I am not sure why it is looking for UDP.

**Comment by JimG777** [comment]
[tcp_hardcoded_proto.txt](https://github.com/davehorton/drachtio-server/files/2147218/tcp_hardcoded_proto.txt)

In this log, I hardcoded proto to "TCP" in findAppropriateTransport() in sip-transports.cpp and it is able to proxy the INVITE to the other client. There is still the ACK problem though.

I see that drachtio-server supports keep-alive packets (/r/n/r/n) which is great. This will help later.

**Comment by davehorton** [comment]
ok, I will fix the issue where it did not select the tcp transport on its own.

What I see in the tcp_hardcoded... file is that the B party puts an address of `sip:+14085550007@10.11.33.97:17777;transport=TCP` in the Contact header of the 200 OK.

So the 200 OK goes back to A with a Record-Route of the proxy and that Contact header for B.
A properly sends an ACK with the Route header of the proxy, and request-uri of the contact above.

So now the proxy properly removes the Route header, and then tries to connect to 10.11.33.97:17777 via TCP.  It looks to me like it can not connect to that address, and that is why the INVITE does not go out.

So I presume that 10.11.33.97 is nat'ed and the public address is 5.5.5.5 ?

Perhaps you are expecting the proxy send the ACK to 5.5.5.5, but I'm not sure that would be right.  I dont think the proxy can make an assumption that 10.11.33.97 is reachable via 5.5.5.5 simply because that is what came back in the Contact header of the 200 OK.  In other words, it is a legitimate use case that a proxy should route an ACK down a different route than the original INVITE.  Your scenario would work if I broke that rule and just routed the ACK the same as the INVITE, but I don't want to do that (globally) since it would break other scenarios

Hmm.  the knowledge that B is nat'ed behind 5.5.5.5 is really something discovered at the time B registers.  But right now I am not keeping an internal mapping of all nat'ed endpoint addresses that have registered.  So when the ACK arrives to get routed the proxy does its normal thing.

I'm sure I can solve it, but I need to give it some more thought I guess on what is the right way to do so.

By the way, do you have an opinion on whether you want your app to be a proxy versus a back-to-back user agent?  Most nat scenarios that I see are combatted primarily using a B2B, which gives the app more direct control of the routing.

**Comment by JimG777** [comment]
Hi, we are using the srf app to act as simple registrar and router between clients. It is mainly for testing, so we thought it could just proxy the requests from client to client. Are you suggesting maybe we could implement it as a b2bua (as in drachtio-b2b-media-proxy)?

To answer your other question, yes, 10.11.33.97 is nat'ed to the 5.5.5.5 public address. In our app, when we receive the REGISTER, we maintain the rport and received IP from the via which are the public IPs. We provide this as the destination when we proxy the INVITE. That is a little of the confusion, why doesn't the INVITE get forwarded to that that IP?

I will look at the b2bua support in srf.

**Comment by JimG777** [comment]
Thank you for your help. I would like to close this issue. A B2BUA seems like a desirable solution.
