### ISSUE TITLE
failed to find transactionId and crash

### ISSUE THREAD

**Issue by salihy** [davehorton/drachtio-server#42]
Drachtio-server crashes every 8-9 days, I inspected logs, only thing I can find is this line:
You can see that after this line, it stops logging till service/system restart.

`2018-07-17 17:13:58.517453 SipDialogController::findAndRemoveTransactionIdForIncomingRequest - failed to find transactionId 79aacf0b-359e-4217-9e0c-112940787577`

logs:
[log.zip](https://github.com/davehorton/drachtio-server/files/2241120/log.zip)

**Comment by davehorton** [comment]
Thanks, will have a look at this.  

BTW, the service should restart automatically if you are using the systemd service file.  Is that not happening?

**Comment by salihy** [comment]
Nope, service doesn't restart automatically, btw I think it's not crashing, it just gets unresponsive.

**Comment by davehorton** [comment]
From the log, it does look like the service restarts -- if you search for the line `Starting drachtio version` which is the first thing logged on startup you will see it occurs a few times right after the crash.

It looks to me like the scenario is a B2BUA call where the A side hangs up before B answers -- i.e. we see a CANCEL recv'ed from A.  However, for some reason this CANCEL is not sent to B.  Then later, we get a final response from B and that is when the crash happens.

I think there are a couple of bugs here -- one definitely in the server when it crashes after receiving the final response from B when the A leg has canceled.  Possibly an issue in the framework where the CANCEL from A should be sent to B but is not.

Could you show me a snippet of the code that is setting up the B2BUA, I assume by calling Srf#createB2BUA ?  That will help me recreate

**Comment by davehorton** [comment]
Also, if you find you can easily recreate by hanging up from the A side while B is still ringing, it would be great to see a log with the log level at debug rather than info showing this scenario

**Comment by davehorton** [comment]
its strange because Srf#createB2BUA *should* be sending a CANCEL to B when it receives a CANCEL from A.  So that is the first thing I want to get to the bottom of.  Can you confirm you are using Srf#createB2BUA? Are you able to recreate this scenario?

**Comment by salihy** [comment]
Ok, I will able to test it tomarrow, I will collect logs and pcap file and let you know, thanks.

**Comment by davehorton** [comment]
great, lets start by trying to simply recreate the scenario where A hangs up while B is still ringing, and for some reason the B leg is not canceled.  With log levels at debug for the drachtio server.

It may not crash, but it is probably related to the issue and should be easily recreatable based on the logs you've shown so far

**Comment by salihy** [comment]
Hi,

My code is here: https://github.com/salihy/Drachtio_B2BMessageManipulation

Here is my log file and pcap file: 
[log.zip](https://github.com/davehorton/drachtio-server/files/2243872/log.zip)

**Comment by salihy** [comment]
Ok, my bad, I restarted nodejs app but forgot to restart drachtio service, I will restart and give you output.

**Comment by salihy** [comment]
Here is the log: 
[log.zip](https://github.com/davehorton/drachtio-server/files/2244995/log.zip)

**Comment by davehorton** [comment]
Can you retest with the latest commit on the develop branch?  I checked in a fix to the problem that I observed on my side, and it would be good to get another debug log of your test case.  

To the extent you can recreate what you had done before, that would be good.  To me it looked like you had a first call, which received a 183 and a 180 and then eventually the app sends a 480 but the A side does not ACK so it resends for a while.  Then a second call that also gets a 180 and 183 but eventually the A side CANCELs.

In any case, please retest with the latest and post logs

**Comment by davehorton** [comment]
were you able to retest with the latest?

**Comment by salihy** [comment]
Yes, this bug didn’t occur since then. DP you want me yok send you logs again? Btw thanks for bug report for our legacy software, i will work on it. I will close this thread and send you current logs as son as possible.
