### ISSUE TITLE
Error sending to remote host name when DNS query returns ipv6 address

### ISSUE THREAD

**Issue by gprat** [davehorton/drachtio-server#43]
Hello,

I'm relatively new to SIP protocol. I'm trying to use Kurento to make SIP calls following this tutorial : https://github.com/daimoc/Kurento-SIP-GW. It uses drachtio server to contact sotphones like linphone. 

I managed to register using the account guiprat@iptel.org and to call the account gprat@sip.linphone.org (i e an account from a different provider) but when I try to contact gprat@iptel.org (i e an account from the same provider), I get the following mistake : 
407 Proxy Authentication Required for INVITE

I tried to add authentication as in the following issue :  https://github.com/davehorton/drachtio-srf/issues/3 but with no luck. I think I may be missing something as I'm just beginning to work with drachtio in peculiar and SIP in general.

I attached the file containing the code related to drachtio and the logs. I just modified the password. 

[log.txt](https://github.com/davehorton/drachtio-server/files/2256998/log.txt)

[sipstack.txt](https://github.com/davehorton/drachtio-server/files/2256995/sipstack.txt)

Could you please help me identify the source of the error ?

Thank you,

Guillaume Prat

**Comment by davehorton** [comment]
Hi there - it looks like you are using an older version of drachtio-srf.  From the logs I can see that you are hitting an old bug that has since been fixed.  Can you verify what version you are running?

**Comment by davehorton** [comment]
Also, from looking at your code, I think it could possibly be greatly simplified by using [srf#createUAC](https://drachtio.org/api#srf-create-uac) rather than [srf#request](https://drachtio.org/api#srf-request).

You might be useful to read [these docs](https://drachtio.org/docs), particularly the part about [how to create and work with SIP dialogs](https://drachtio.org/docs#sip-dialogs).

I can also provide some assistance if needed.

**Comment by davehorton** [comment]
here is a [code snippet](https://drachtio.org/docs#authentication) showing how to do authentication when sending an INVITE.

Please make sure to update to [drachtio@4.3.4](https://www.npmjs.com/package/drachtio-srf) though

**Comment by davehorton** [comment]
Oh, I see the Kurento project is using an old version of the 'drachtio' package.  Are you the one maintaining this?  If so, you should update to using drachtio-srf instead, and take advantage of some of the higher-level operations that are available.

Just to explain the history behind this, the 'drachtio' package was a relatively low-level SIP framework, and originally 'drachtio-srf' was a package that added in some higher-level concepts.  I have since bundled the functionality that was once in 'drachtio' into 'drachtio-srf', so the use of 'drachtio' is deprecated.  You should only include 'drachtio-srf' into your project -- the low level stuff is still there if you need it (and it is used by the higher-level functions) but generally you will find it easier to use the dialog-forming functions (srf.createUas, srf.createUAC, srf.createB2BUA).

**Comment by gprat** [comment]
Thank you for your answers. First I'm not the one maintaining the github repository with which I try to make SIP calls. But I might suggest some modifications if I manage to get it to work. 

I updated the package drachtio-srf to 4.3.4. I deleted all references to drachtio and used drachtio-srf instead. I don't have 407 error anymore and I manage to perform the call. But I don't have sound or image. And the call quits after 31 seconds. Here are the logs : 

[logSrfRequest.txt](https://github.com/davehorton/drachtio-server/files/2258398/logSrfRequest.txt)
 
I also tried using the code snippet you suggested. I found two mistakes in this code snippet : 
` missing after "`call failed with ${err})"
createUAC instead of createUac
When I omit to precise the From in the header I can make a connection but I appear in the invite as the ip address of my computer. And I have no sound or video.
I tried to add the From in the header and I managed to perform the call. But still no sound or video. And exit after 31 seconds.

[logUAC.txt](https://github.com/davehorton/drachtio-server/files/2258399/logUAC.txt)

and here is the code updated (with the second approach commented)

[sipstack2.txt](https://github.com/davehorton/drachtio-server/files/2258409/sipstack2.txt)

Thank you again for your help.

Guillaume Prat

**Comment by davehorton** [comment]
Could you do me a favor and update to the latest drachtio-server (on the develop branch) as well?

There is a new config parameter [udp-mtu](https://drachtio.org/docs/drachtio-server#udp-mtu) which I would like to have you set to 4096, i.e.

```xml
<sip>
   <udp-mtu>4096</udp-mtu>

```
Part of the issue is that drachtio is sending the outbound invite tcp instead of udp based on the size of the message, but this isnt necessary and is probably causing issues.

Once you do that and retest can you provide the logs again?

**Comment by gprat** [comment]
Thank you for your answer. Unfortunately I won't have access to my server until monday. I will send you the logs once I have performed the update and the modification of the parameter.

Have a nice weekend.

Guillaume Prat

**Comment by gprat** [comment]
Hello,

I have performed the update of drachtio-server and modified the paramater udp-mtu. When I try to connect using srf.invite I still have no sound or video and the call terminates after a few seconds. One of the softphones I use (blink) indicates that no ACK has been received. Here are the logs : 

[logSrfRequestupdated.txt](https://github.com/davehorton/drachtio-server/files/2262395/logSrfRequestupdated.txt)

There is no longer an indication of a ACK issue when I use createUAC. But still no sound or video. Here are the logs : 

[logUACupdated.txt](https://github.com/davehorton/drachtio-server/files/2262399/logUACupdated.txt)

Thank you for your help,

Guillaume Prat

**Comment by davehorton** [comment]
There seems to be an issue on the server that is related to supporting ipv6 and ipv4 simultaneously.  To work around the problem for now, can you change you 'contact' configuration in drachtio.conf.xml from

sip:*;transport=udp,tcp

to your specific IP

sip:10.196.160.34;transport=udp,tcp

?  Or, alternatively, disable ipv6 on your laptop?

Let me know if you still have problems after doing this.  Meanwhile I will look into the issue when both ipv6 and ipv4 are available

**Comment by davehorton** [comment]
Created a gist of the relevant log snippet showing the problem: https://gist.github.com/davehorton/87b050bcdec6913584f204c0ed4ada12

what happens:
- we start by selecting a local ipv4 endpoint to send from for the dns name
- the DNS request then returns an AAAA (ipv6) address
- we try to send to that address from the local ipv4 and it fails
- we fall back to ipv4, but leaving an ipv6 Contact header

**Comment by gprat** [comment]
This might be linked to the issue, there is a file that defines certain variables including the IP adress of the sdp offerer (serverPublicIP) and configuration for drachtio (used in srf.connect). 

I tried different IPs, notably for serverPublicIP as I was unsure if I should enter the IP of the server (10.196.160.34), the IP of the machine on which I access to the page that is making the communication (10.196.160.106), or the public IP of my network (same for the two machines) .

Here is the file : 

[config.txt](https://github.com/davehorton/drachtio-server/files/2262579/config.txt)

I'll try to edit drachtio.conf.xml and let you know.

**Comment by davehorton** [comment]
it looks like serverPublicIP is meant to be the ip address of the drachtio server.

**Comment by gprat** [comment]
Hello,

I have disabled IPv6 both on my laptop and my server and I changed the contact parameter as indicated.

Here are the logs :
 
[logIPv6Disabled.txt](https://github.com/davehorton/drachtio-server/files/2262759/logIPv6Disabled.txt)

**Comment by davehorton** [comment]
OK that log looks better -- the INVITE / 200 OK / ACK all look correct.  So the signaling looks good.  Are you still having an issue with media?

**Comment by davehorton** [comment]
Your INVITE is offering audio and video.  The SDP in the 200 OK has disabled video and is only offering audio, using OPUS codec, ie it looks like this:

```
m=audio 22250 RTP/AVPF 96
c=IN IP4 212.79.111.155
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=sendrecv
a=zrtp-hash:1.10 5c7a1d7d949fd612dc00366578a99d4f8f92b69043e9ecc70e6f7f70ee1a2b20
m=video 0 RTP/AVPF 104 105
c=IN IP4 10.196.160.106
a=inactive
```

Then you get a BYE with reason 'RTP timeout'.  So it seems like the media server is not sending RTP to that address.  

At this point, the issue seems to be with the media server (that I am not familiar with) not the drachtio SIP server

**Comment by gprat** [comment]
I have an explication for both  points. It's the softphone I am using that disables the video (blink in this case). When I am using another one (Jitsi) I have this in the sdp in the 200 OK : 

v=0
o=- 0 0 IN IP4 212.79.111.155
s=-
c=IN IP4 212.79.111.155
t=0 0
m=audio 22760 RTP/AVPF 96 0
a=rtpmap:96 opus/48000/2
a=fmtp:96 usedtx=1
a=rtpmap:0 PCMU/8000
a=sendrecv
a=ptime:20
m=video 14038 RTP/AVPF 104 105
a=rtpmap:104 VP8/90000
a=rtpmap:105 H264/90000
a=fmtp:105 profile-level-id=4DE01f
a=sendrecv

See below for the complete log : 

[logJitsi.txt](https://github.com/davehorton/drachtio-server/files/2262967/logJitsi.txt)

The timeout might be due to a parameter in the file config.js : 
config.maxCallSeconds = 60;

But still no sound or video. For you the logs are not showing any problem of any kind and so the call should proceed normally ? There might be an issue with Kurento but was surprises me is that I was able at the beginning to perform a call from a provider to another provider.

**Comment by davehorton** [comment]
Yes, the signaling looks fine now.  Once you get the SDP back in the 200 OK, I presume you are instructing the Kurento media server to send there, and it seems like for some reason it is not.

**Comment by gprat** [comment]
Sorry. I think I know where the problem comes from. I was too speedy when I switched to drachtio-srf and I removed code that I shouldn't. I'm working on it and I'm keeping you updated.

**Comment by gprat** [comment]
A thousand apologies. I had effectively deleted some code that I shouldn't. I have performed some corrections and now it's working. I still have some tests to do and I have some errors appearing when I use some softphones (blink does'nt receive ACK). But I managed to make a call using Jitsi and iptel accounts.

Thank you so much for your help. I will keep you informed of the progress of my tests and I might have some other errors to report. But I just wanted to tell you that we managed to get it to work.

**Comment by davehorton** [comment]
Excellent!

On Aug 6, 2018, at 12:11 PM, gprat <notifications@github.com> wrote:

A thousand apologies. I had effectively deleted some code that I shouldn't. I have performed some corrections and now it's working. I still have some tests to do and I have some errors appearing when I use some softphones (blink does'nt receive ACK). But I managed to make a call using Jitsi and iptel accounts.

Thank you so much for your help. I will keep you informed of the progress of my tests and I might have some other errors to report. But I just wanted to tell you that we managed to get it to work.

**Comment by gprat** [comment]
Hello, 

I still have errors but I think it is linked to one of the SIP account providers I am using and not to drachtio. Because when I use iptel.org account it works all the time. 

I have modified the code included in the project https://github.com/daimoc/Kurento-SIP-GW to update it to drachtio-srf with the latest version and to include registration and authentication. I've seen you opened an issue in this project in order to update it to the latest version of drachtio.  If you agree with it I can suggest in this issue to share my code so that the project is up to date and people will no longer encounter the errors you helped me solve.

Thank you again for your help.

Guillaume Prat
