### ISSUE TITLE
Feature Request: add options to specify admin port, IP and secret on command line

### ISSUE THREAD

**Issue by busseyl** [davehorton/drachtio-server#45]
Reviewing the code I only see the config class referencing the admin IP, port and secret values in the XML config file:

```<admin port="9022" secret="cymru">127.0.0.1</admin>```

When running a Docker container it is less desirable to hard-code these types of properties in a configuration file that requires complex configuration (file) management. This is especially true when setting these types of properties in a very dynamic environment with service discovery.

Ideally, these values would be referenced/passed via environment variables or the command line parameters. This concept is similar to the way that we can pass --contact and --external-ip config parameters.

Perhaps (very likely!) I'm overlooking something in the code but I don't see any way to perform this type of configuration.

Thanks for releasing such a great project to the open source world!

Regards,
Lucas

**Comment by busseyl** [comment]
Update: I see in the README that the admin port can be specified on the command line, but I don't see the listening admin IP or secret in the list of available command line parameters.

**Comment by davehorton** [comment]
you're right, I have not exposed those.  I will look into adding those...

**Comment by davehorton** [comment]
here is the best documentation on command line arg FYI

https://drachtio.org/docs/drachtio-server#command-line-arguments

**Comment by davehorton** [comment]
added in v0.7.4-rc1
