### ISSUE TITLE
Feature Request: add a SSL/TLS-encrypted admin port so that the control messages aren't sent in plain text

### ISSUE THREAD

**Issue by busseyl** [davehorton/drachtio-server#46]
This could be accomplished using third-party software such as HAProxy to provide an SSL-termination TCP endpoint.

However, it could be rather useful to provide out-of-the box encryption. It looks like the libraries are already included in the project for SIP over TLS.

Is this something on the "roadmap"?

**Comment by davehorton** [comment]
agree, I have thought this could be useful.  It's been in the back of my head (closest thing to a roadmap, haha) for a while.  It's something a expect to be able to get to in the 1-3 month timeframe.

**Comment by rnewman** [comment]
This is very relevant to my interests; any news on this, @davehorton?

**Comment by davehorton** [comment]
I am on holiday until October 28. I think I can get this done in early November.

**Comment by rnewman** [comment]
Great; thanks for letting me know, @davehorton. Have a good holiday!

**Comment by davehorton** [comment]
I've added tls support - it requires a build of the drachtio server on the head of the develop branch (latest docker image should have it as well), and drachtio-srf@4.4.0

Some instructions [can be found here](https://drachtio.org/docs#using-tls-to-encrypt-messages-between-application-and-server)

I'll leave this issue open for a bit in case you are able to test and can provide feedback

**Comment by rnewman** [comment]
This looks really thorough, @davehorton; thank you. Will try to test this out this week and get you some feedback from use.

**Comment by davehorton** [comment]
did you have a chance to test this feature?

**Comment by rnewman** [comment]
The team got pulled away before completing end to end testing this week, @davehorton; I was hoping to have a concrete report from them by this morning, but it didn’t happen. 

I did read all of the docs and most of the diff; the exposure of the `tls` options dictionary makes me pretty confident that this will work for us. I’m OK with closing this issue; we can file another if we run into any snags. 

Thanks again for making this change.

**Comment by davehorton** [comment]
sounds good!
