### ISSUE TITLE
Confused on license

### ISSUE THREAD

**Issue by hyandell** [davehorton/drachtio-server#50]
Hi Dave,

I can see the project is MIT ( per LICENSE file ) but I also see a GPLv3 file in docs/COPYING. What does the docs/COPYING file relate to?

**Comment by davehorton** [comment]
Looks like an oversight on my part, or an inadvertent build artifact that got checked in.  I'll fix it, but the MIT license governs the use of this project.

**Comment by rnewman** [comment]
Thanks for clarifying, @davehorton.
