### ISSUE TITLE
Mid call Mobility/ Wifi-Cell Network Handoff Consideration?

### ISSUE THREAD

**Issue by andrewvmail** [davehorton/drachtio-server#55]
Hi Dave, 

Could use your insights on this.

I can get network handoff to work with MICE and continuous ice gathering set. RTP automatically reflows to the other interface. Websocket connection reconnects automatically. I send register again to  Drachtio. But after this point only the device that did the network handoff can send a bye. 

Thanks!

**Comment by davehorton** [comment]
I'm not quite clear on the setup here.  can you outline the servers / SIP clients and describe what sort of failover you are doing?  I'm unclear for instance if the drachtio server is on a server that is being killed or something..

**Comment by andrewvmail** [comment]
Okay so we have 2 SIP/WebRTC clients which are both mobile phones, a Drachtio server and a STUN/TURN server. The network handoff I'm referring to is when one of the client jumps network between wifi to cellular. Like if he goes to his car while on the phone and go out of wifi coverage.

**Comment by andrewvmail** [comment]
Hi Dave,

I got a bare test client into the app store just for testing things on the cellular network.
https://itunes.apple.com/gb/app/drachtio-webrtc-ref-client/id1438951054

If you want to see the behaviour I'm describing assuming you have an ios device
You can setup the backend like this https://gist.github.com/andrewvmail/4d1034ff19b123565375f8681c6f7556
and connect two clients to it then disable wifi while your in call on one client and you can see handoff working and the bye not getting relayed.

Just a note the web version doesn't work on non secure server thats not localhost. So to test between mobile and web with server in the public internet drachtio need to be running with certs.

**Comment by davehorton** [comment]
Thanks, I'm back in action (or at least making my way back, in airports/air for the next 22 hours)!  

I will try to recreate using your instructions, but if you had a full drachtio log available showing the scenario I would have a look at it in the meantime

**Comment by andrewvmail** [comment]
Nice! hope you had a good time, 22 hours thats one long flight. guessing you went to other side of the world.

Okay here is the drachtio log showing the scenario 

https://gist.github.com/andrewvmail/cc1344c6e5740d8f3d8f5af04daa729e

so my ipad username 4321 sends invite to iphone 1234
they started on the same local network and drachtio + coturn  is on the internet.
got 2 way audio 
i take ipad out of wifi it jumps to 3g few second no audio
then got 2 way audio again
then i hangup using iphone and ipad does not receive the bye

Thanks and safe flight

**Comment by davehorton** [comment]
I've created a branch called 'mid-call-network-handoff' with an attempted fix for this.  Let me know if you are able to test it.  I can also push a docker image if you prefer that.

**Comment by andrewvmail** [comment]
Yes can test this. Will let you know the result.

**Comment by davehorton** [comment]
great, I added some logging so if it fails maybe you can post another log

**Comment by andrewvmail** [comment]
Hi Dave, 
Just did some testing and the bye still didn't get relayed to the client that jumped.
Log here:
https://gist.github.com/andrewvmail/34c7b0d83998b5a2a839c14576d70837

**Comment by davehorton** [comment]
I think I see the issue.  At your convenience, can you retest with the latest on that branch?

**Comment by andrewvmail** [comment]
Yes on it.

**Comment by andrewvmail** [comment]
Hi Dave, tested again bye still not going through.
Log here:
https://gist.github.com/andrewvmail/450e656a3125c4bda04f11994a5eb383

**Comment by davehorton** [comment]
dang it. I just checked in another change.....can you retest that when possible?

**Comment by andrewvmail** [comment]
yeah retesting now

**Comment by andrewvmail** [comment]
Okay that did it!

**Comment by davehorton** [comment]
finally!  Many thanks for your testing.  I will merge into the develop branch now

**Comment by andrewvmail** [comment]
Cool thanks Dave. Closing
