### ISSUE TITLE
Heartbeat metrics - logfile/syslog alternative?

### ISSUE THREAD

**Issue by garnatha** [davehorton/drachtio-server#58]
Hi Dave - have you considered providing an alternative method for data/metric extraction from Drachtio other than log/syslog/console? The current format of the 30 second heartbeat requires some pretty nasty log extracting and parsing, a storing of value counters (to obtain metrics that have increased since last heartbeat) and could be prone to errors based on the file entry formats. 

What would be very useful is the ability to connect to the/an admin port and pull or subscribe to events on demand. The logic here is that one could connect to Drachtio, extract data and process accordingly in one single application rather than having to send data to log/syslog, filter, scan, parse and then have a process handle the scrubbed info. 

The data in the heartbeat is fantastic! Would just love a simpler way to break it down. 
Having the data dumped as a single json blob in a dedicated file would also be very nice to work with! 

Many thanks

Gar

**Comment by davehorton** [comment]
thanks, that's a great idea. Will look into this in the near term after I finish some other changes I am working on.

**Comment by garnatha** [comment]
Just some further observations that would be worth taking into consideration since I've been working more around this the past few days...

- The Watchdog could be simpler if it dumps each of the 69 metrics at the same time rather than  individual log entries. Reason for this is that it can be error prone when receiving & processing data in bursts. 

- If the watchdog was providing incremental metric values since last heartbeat rather than total counters since startup that would be much more useful. With the fact that each metric is a counter of data since the process started its an extra step to take the watchdog reported data, compare it to an on-box stored cache and subtract the previous cached value before doing something with the actual metric. When combining these counters with the fact that each metric is posted individually results in some pretty heavy file IO performing this 69 times. 

- The usage of "Timer X Queue Size" for both SipDialogController & ClientController makes it difficult to separate the metrics since they are identically named. The only help is a few log entries back the logging of the section title SipDiaglog or Client which makes handling these metrics very challenging. Naming them differently would solve this problem - ideally something like a prefix:

ClientTimerAQueueSize
SipDialogTimeAQueueSize

**Comment by davehorton** [comment]
Closing this issue as metrics now provided via prometheus.  Please open new issue if those stats are not sufficient for your purposes.
