### ISSUE TITLE
No events hitting syslog

### ISSUE THREAD

**Issue by garnatha** [davehorton/drachtio-server#59]
I can't seem to get any messages to hit a local syslog server - it just appears that nothing is being sent from Drachtio. Nothing in the logs on full verbosity indicate a problem and both file logging and console sending seem to behave fine. 
I've verified the local syslog server is listening & accepting other localhost requests. 

Have i missed something or is there anything else I can explore to validate what Drachtio is doing (or not) with syslog sending?

```
       <syslog>
            <address>127.0.0.1</address>
            <port>515</port>
            <facility>local6</facility>
        </syslog>
```

Version: drachtio-server-v0.8.0-rc1

Thanks!

Gareth

**Comment by davehorton** [comment]
Hmm, I have not used the syslog logging facility in a while (switched my usage to file logging), I wonder if I have a regression bug.  I'll have a look...

**Comment by davehorton** [comment]
hmm, at first glance in my test it seemed like I was sending.  Can you take a wireshark on your local interface and see if you see any syslog messages being sent to udp port 515 ?

**Comment by garnatha** [comment]
Progress, tcpdump has explained things - Drachtio's sending syslog but to port 514 when I've configured port 515. Thats good enough for me to work with and likely enough for you to identify a potential bug ;-) Thanks for the speedy responses.

**Comment by garnatha** [comment]
https://github.com/davehorton/drachtio-server/blob/782d405e5ca48737afb9a4286806c001c8db49d5/deps/boost_1_63_0/boost/log/sinks/syslog_backend.hpp#L239

**Comment by davehorton** [comment]
this is fixed in the latest checkin on the develop branch, also tagged as v0.8.0-rc2

**Comment by garnatha** [comment]
Thanks Dave, but unfortunately this doesn't seem resolved in rc2. I'm pretty confident I'm running the patched release but still syslog is defaulting to port 514 when configured as 515. 
Can you confirm the behaviour for you?

**Comment by davehorton** [comment]
yes, my bad I thought I committed the fix in that release, but later saw that I missed committing it.  If you grab rc3 I think you should have it

**Comment by garnatha** [comment]
Looking good - thanks Dave.
