### ISSUE TITLE
Crash happening on startup on loading regex code

### ISSUE THREAD

**Issue by CelsoGalo** [davehorton/drachtio-server#60]
Hello Dave! So nice your work on this. We are start using it in a very important project at Atos group.

I just downloaded the last version and checked out the latest from develop. Compilation runs fine... But a crash happens when starting the drachtio-server. Please look the attached picture:
![selection_003](https://user-images.githubusercontent.com/5338772/48912064-c4716300-ee5b-11e8-896f-67a5e1803d2e.png)

I was having no problem on my previous compilation (that I cloned some weeks ago). By comparing the code, I saw that you made changes on it :-), so I am assuming that a new bug was introduced.

Can you please address that? Thank you so much!

**Comment by CelsoGalo** [comment]
I am compiling on OpenSuse Leap 42.3. I know it is not officially supported :-), but it was working fine before this change.

**Comment by davehorton** [comment]
Hmm, this is interesting.  One of the changes was to remove boost::regex in favor of std::regex.  I am not sure why it would segfault creating that regex.  I've not seen that myself in my testing on other distros.  Can you include the drachtio log (with loglevel debug) leading up to this? I will also see if I can spin up an OpeSuse Leap VM to test with

**Comment by CelsoGalo** [comment]
Yes... Just to confirm, the v0.8.0-rc2 does not present the error. Just a moment, I will try to get the logs.

Hmm... What would be the minimum GCC that I should use? My default is v4.8, but our build system already supports the v7.3.1.

**Comment by davehorton** [comment]
The Makefile.am will now try to build with -std=c++-17 if available, -std=c++-11 if not.  I guess the fact that it is compiling ok means your build environment is satisfactory.

There were major changes in v0.8.0-rc3 to eliminate a lot of boost stuff that has been incorporated into the c++ standard.  This seems somehow related.

**Comment by CelsoGalo** [comment]
I found that that I am using "-std=gnu++11" and this is apparently failing:

checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking whether g++ -std=gnu++11 supports C++17 features by default... no
checking whether g++ -std=gnu++11 supports C++17 features with -std=c++17... no
checking whether g++ -std=gnu++11 supports C++17 features with +std=c++17... no
checking whether g++ -std=gnu++11 supports C++17 features with -h std=c++17... no
checking whether g++ -std=gnu++11 supports C++17 features with -std=c++1z... no
checking whether g++ -std=gnu++11 supports C++17 features with +std=c++1z... no
checking whether g++ -std=gnu++11 supports C++17 features with -h std=c++1z... no
configure: No compiler with C++17 support was found
configure: WARNING: C++17 is not yet standardized, so the checks may change in incompatible ways anytime

**Comment by davehorton** [comment]
that should be ok (I think) since you have
```
checking whether g++ supports C++11 features with -std=gnu++11... yes
```

**Comment by davehorton** [comment]
OK I have a VM running opensuse leap 42.3 but I am not familar with the package manager.  Can you please give me the full set of instructions on how to install the dependencies so I can build?  RIght now, for instance, I am unable to figure out how to install the libcurl-openssl-dev dependency...

**Comment by davehorton** [comment]
well, here is the problem:

https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

Is there any chance you can upgrade gcc to 4.9 above?

**Comment by CelsoGalo** [comment]
Hey Dave, sorry for the delay. My production system offers me also gcc 7.3. The crash cannot be seen! Thanks a lot!

**Comment by davehorton** [comment]
Oh, that's great!  I guess I have to give some thought to whether requiring gcc 4.9 or above is too restrictive...for now I guess I will leave as is.

Is this a satisfactory enough outcome to close this issue?

**Comment by CelsoGalo** [comment]
Let me just respond your question above about which libcurl4 I am using on OpenSuse leap 42.3.

# ldd /usr/local/bin/drachtio
	libcurl.so.4 => /usr/lib64/libcurl.so.4

# rpm -q --whatprovides /usr/lib64/libcurl.so.4
libcurl4-7.37.0-33.1.x86_64

So I think it is this one (currently pointing to Version 7.37.0 Size 349 KB openSUSE Leap 42.3):
https://software.opensuse.org/package/libcurl4

**Comment by CelsoGalo** [comment]
Sure, very satisfactory, let me close. Thank you so much.
