### ISSUE TITLE
DrachtIO and Homer

### ISSUE THREAD

**Issue by haeferer** [davehorton/drachtio-server#61]
Hi,

we are trying to get get HEP running. We had installed Homer5-Docker and the HEP3 Packages are reaching the container (port 9060). 
But it seems homer does not even recognize these packages

Do you have a defined a enviroment in which homer integration does work?

**Comment by davehorton** [comment]
I want to make sure I understand the current state.  You have configured the drachtio server to send HEP to your homer instance, and when you take a wireshark trace you can see that the drachtio server is in fact sending HEP to the expected IP:port.  Yet you do not see the SIP transactions in homer.

Is that correct?

**Comment by haeferer** [comment]
Yep exactly (using ngrep within kamailio instance)

**Comment by haeferer** [comment]
Package starts with "HEP3.........................." and ends with the SIP Package content

**Comment by haeferer** [comment]
We tried the Single Instance Version (docker run) and the Multi Instance Version (docker-compose). Result ist the same
Homer WebApp is working, but every panel is empty except a few stating : "Could not resolve all promises"

PS we are running docker for windows  on windows 10

**Comment by davehorton** [comment]
It sounds like a homer problem.  I'm not a homer expert, but one of the problems I faced in the past was that the cron job that needs to run to rotate the mysql tables that homer writes to, had not run / was not running.  Thus the tables that homer wanted to write sip transactions to did not exist, and the writes failed.

Note sure if this is your problem, but I suggest logging into the mysql database, and listing the tables in the 'homer_data' database to see if you get what's expected.  For instance, there should be a table named `sip_capture_call_20181128`.  This is incoming HEP messages for sip invites would be written.

Here are the commands I used....note I was running homer in kubernetes, so the commands are different for pure docker
```
kubectl -n homer exec -ti homer-complete-163319440-kp88c -c homer-kamailio -- /bin/bash

mysql -u homer -p3DZcYXeyGLCY -h cloudsql.default.svc.cluster.local homer_data

mysql> show databases;
+---------------------+
| Database            |
+---------------------+
| information_schema  |
| homer_configuration |
| homer_data          |
| homer_statistic     |
+---------------------+
4 rows in set (0.00 sec)

mysql> use homer_data;

Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+-----------------------------------+
| Tables_in_homer_data              |
+-----------------------------------+
| isup_capture_all_20180115         |
| isup_capture_all_20180116         |
| isup_capture_all_20180117         |
| logs_capture                      |
| report_capture                    |
| rtcp_capture                      |
| rtcp_capture_all_20180115         |
| rtcp_capture_all_20180116         |
| rtcp_capture_all_20180117         |
| sip_capture_call_20180115         |
| sip_capture_call_20180116         |
| sip_capture_call_20180117         |
| sip_capture_registration_20180115 |
| sip_capture_registration_20180116 |
| sip_capture_registration_20180117 |
| sip_capture_rest_20180115         |
| sip_capture_rest_20180116         |
| sip_capture_rest_20180117         |
| webrtc_capture                    |
| webrtc_capture_all_20180115       |
| webrtc_capture_all_20180116       |
| webrtc_capture_all_20180117       |
+-----------------------------------+
22 rows in set (0.01 sec)
```

**Comment by haeferer** [comment]
Thx a lot we will check this

**Comment by davehorton** [comment]
I recall around this time I opened this issue with homer-cron

https://github.com/sipcapture/homer-docker/issues/61

**Comment by ttitze2** [comment]
I just had a look at the database (after struggling with the Password until I realized that it is void). The tables "Capture_all_<date>" are empty.

**Comment by davehorton** [comment]
are there any date-stamped tables, like the ones I show above?  If not, you need to run the homer cron job.  That is supposed to run daily, and creates the next 3 days worth of tables...

**Comment by ttitze2** [comment]
Yes! Tables 
"logs_capture_all_20181127", … 30, 
"sip_catpture_call_20181127",.. 30,
 "sip_capture_rest_20171127",...30, etc. -- beginning from day before yesterday until tomorrow --
do not contain any records at all although when listening at port 9060 we can watch this sip-data arriving at the docker box running "heplify-service".

**Comment by haeferer** [comment]
It seems that sipcapture/homer-docker:latest is very old (9 Months)
we have changed to sipcapture/homer-docker:master, and magically it works :(
