### ISSUE TITLE
Bind to Specific Interface

### ISSUE THREAD

**Issue by haeferer** [davehorton/drachtio-server#63]
Is it possible to bind the server to a specific interface? Right now the Server chooses the wrong interface for outgoing UDP (in a specific scenario with our internal phones).

**Comment by davehorton** [comment]
yes, see

https://drachtio.org/docs/drachtio-server#contacts

and 

https://drachtio.org/docs/drachtio-server#command-line-arguments

**Comment by haeferer** [comment]
Ok, you parse the Interface from contact

Perfect,

Thx

Von meinem iPhone gesendet

Am 06.12.2018 um 14:15 schrieb Dave Horton <notifications@github.com<mailto:notifications@github.com>>:


yes, see

https://drachtio.org/docs/drachtio-server#contacts

and

https://drachtio.org/docs/drachtio-server#command-line-arguments
