### ISSUE TITLE
Providing Contact Header

### ISSUE THREAD

**Issue by haeferer** [davehorton/drachtio-server#65]
Hi, 

since we are struggling on NAT with out internal phones, we try to provide a predefined "Contact" Header (`` <sip:192.168.100.200:23792>``) for a INFO Request.
We try to send this Request, but it seems the DrachtServer sees our contact, but overrides it again ```outgoing_update_contact() outgoing_update_contact: updating contact to  udp/172.22.17.11:5060``` 

is there a way to supress this behavior, or to change the contact information for an dialog.

a little more context: we use RFC3581- symmetric response routing. Everything works as excpected, except the final BYE from Remote - so we try to update out contact informations to the informations provided by the responses earlier - using "port" and "received" in VIA Responses)
```
2018-12-07 10:06:14.256214 Client::processMessage - got request with 4 tokens
2018-12-07 10:06:14.256246 Client::processMessage - request id 4f030aa4-2b3c-4b7a-8b11-17f2f3539e32, request type: sip transaction id: , dialog id: bd60d3a0-a110-464b-9c65-283ed78e14a8
2018-12-07 10:06:14.256276 Client::processMessage - sending a request inside a dialog (dialogId provided)
2018-12-07 10:06:14.256705 ClientController::addAppTransaction: transactionId fe5ddf69-a2f2-4a02-b61f-5eb28c298ea6; size: 3
2018-12-07 10:06:14.256743 ClientController::addApiRequest: clientMsgId 4f030aa4-2b3c-4b7a-8b11-17f2f3539e32; size: 1
2018-12-07 10:06:14.256825 SipDialogController::doSendRequestInsideDialog dialog id: bd60d3a0-a110-464b-9c65-283ed78e14a8
2018-12-07 10:06:14.257058 makeTags - Adding well-known header 'contact' with value '<sip:192.168.100.200:23792>'
2018-12-07 10:06:14.257433 SipDialogController::doSendRequestInsideDialog - defaulting request uri to sip:192.168.100.53:5060
2018-12-07 10:06:14.257516 nta.c:2753 nta_tpn_by_url() nta: selecting scheme sip
2018-12-07 10:06:14.257691 nta.c:2595 outgoing_update_contact() outgoing_update_contact: updating contact to  udp/172.22.17.11:5060
2018-12-07 10:06:14.257905 tport.c:3285 tport_tsend() tport_tsend(0x12324a0) tpn = */192.168.100.53:5060
2018-12-07 10:06:14.257946 tport.c:4085 tport_resolve() tport_resolve addrinfo = 192.168.100.53:5060
2018-12-07 10:06:14.258382 tport.c:3531 tport_send_msg() tport_vsend returned 351
2018-12-07 10:06:14.258480 send 351 bytes to udp/[192.168.100.53]:5060 at 10:06:14.258058:
INFO sip:192.168.100.53:5060 SIP/2.0```

**Comment by davehorton** [comment]
I need to understand the network better.  So your phones are behind a NAT, and it seems like the drachtio server is behind the NAT as well?  And then you are sending to a public SIP server of some kind?  Is that accurate?  If so, what is the far end SIP service you are sending to?

**Comment by haeferer** [comment]
Let me explain...
We make calls to out internal phone (direct, without an Asterisk etc.). These phones are within a different network (in the sample 192.168.100.53).
Out DrachtIo (in 172.22.17)  reaches this phone with an Proxy(192.168.99.100).
Invite, Connect and RTP everything works perfect, cause of the rport Parameter. 

Problem: If the phone 192.168.100.53 trys to send a BYE it uses not the ip/port from the invite, it uses the information in the contact header, and fails... (Please note, this problem exists not with our external carrier)!

So we want to send an INFO Request after the first OK, with an manipulatet contact header (using the informations we already got from the provisional responses) to make the BYE work.

If we set the Contact Header, the DrachteServer removes and set his version of the Contact Header

**Comment by davehorton** [comment]
when you say you are using a proxy at 192.168.99.100, so you mean a 3rd party SIP proxy of some kind?  If so, then the solution would be to have the proxy use Record-Route, so the BYE also goes through the proxy.

**Comment by haeferer** [comment]
No, this is a Network Proxy, same as if your are connecting your business-network to the internet

**Comment by davehorton** [comment]
OK you mean a router.  So the drachtio server is not in the 192.168.0.0/16 network, it is at the public address 172.22.17.11 ?  If so, why can't the phones reach this address when sending the BYE to it ?

**Comment by haeferer** [comment]
Making calls to our carrier (using our proxy to the internet) works. The Carrier uses the same IP and Port from the Invite Request to send the BYE for the call.

**Comment by davehorton** [comment]
you said the phone was sending the BYE, not the drachtio server....

**Comment by haeferer** [comment]
> OK you mean a router. So the drachtio server is not in the 192.168.0.0/16 network, it is at the public address 172.22.17.11 ? If so, why can't the phones reach this address when sending the BYE to it ?

Because all IP's from the 172.22.17.xxx network act as the same Originating IP for the phone.  As described in 3581 the Phone should simply send responses to the same IP and Port (Symmetric) the request comes from

**Comment by davehorton** [comment]
responses - yes.  But the BYE is a request, and should be sent the address in the Contact header.

I need more clarity on this -- the call is successfully set up, and then which side sends the BYE?

Can you remove all of your code that is setting the Contact etc. and just show me a full drachtio log starting with the INVITE and ending with the failed BYE.

**Comment by haeferer** [comment]
> you said the phone was sending the BYE, not the drachtio server....

Yes, but to the wrong IP and Port 

here is the log (from the phone)

everything works great using

`` Sent to udp:192.168.100.200:17694 at Jan 2 05:06:03 (509 bytes): ``

but the phone decides to send the BYE 
to 
`` Sent to udp:172.22.17.11:5060 at Jan 2 05:06:07 (502 bytes): `` 

```
Received from udp:192.168.100.200:17694 at Jan 2 05:06:03 (971 bytes):

INVITE sip:192.168.100.53 SIP/2.0
Via: SIP/2.0/UDP 172.22.17.11;rport;branch=z9hG4bK8mjDKN5NHer9Q
Max-Forwards: 70
From: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
To: <sip:192.168.100.53>
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 131758205 INVITE
Contact: <sip:172.22.17.11:5060>
Content-Type: application/sdp
Content-Length: 549
Alert-Info: <http://www.notused.com>;info=alert-autoanswer;delay=3

v=0
o=FreeSWITCH 1544167635 1544167636 IN IP4 172.22.17.11
s=FreeSWITCH
c=IN IP4 172.22.17.11
t=0 0
m=audio 20886 RTP/AVP 0 102 103 8 101 104 106
a=rtpmap:0 PCMU/8000
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=0; cbr=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:103 SPEEX/32000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:104 telephone-event/48000
a=fmtp:104 0-16
a=rtpmap:106 telephone-event/32000
a=fmtp:106 0-16
a=ptime:20
a=sendrecv
Sent to udp:192.168.100.200:17694 at Jan 2 05:06:03 (509 bytes):

SIP/2.0 180 Ringing
Via: SIP/2.0/UDP 172.22.17.11;rport=17694;branch=z9hG4bK8mjDKN5NHer9Q;received=192.168.100.200
From: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
To: <sip:192.168.100.53>;tag=ey1s5tnvyz
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 131758205 INVITE
User-Agent: snom320/8.7.5.35
Contact: <sip:192.168.100.53:5060>
Allow: INVITE, ACK, CANCEL, BYE, REFER, OPTIONS, NOTIFY, SUBSCRIBE, PRACK, MESSAGE, INFO, UPDATE
Allow-Events: talk, hold, refer, call-info
Content-Length: 0

Sent to udp:192.168.100.200:17694 at Jan 2 05:06:05 (824 bytes):

SIP/2.0 200 Ok
Via: SIP/2.0/UDP 172.22.17.11;rport=17694;branch=z9hG4bK8mjDKN5NHer9Q;received=192.168.100.200
From: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
To: <sip:192.168.100.53>;tag=ey1s5tnvyz
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 131758205 INVITE
User-Agent: snom320/8.7.5.35
Contact: <sip:192.168.100.53:5060>
Allow: INVITE, ACK, CANCEL, BYE, REFER, OPTIONS, NOTIFY, SUBSCRIBE, PRACK, MESSAGE, INFO, UPDATE
Allow-Events: talk, hold, refer, call-info
Supported: timer, replaces, from-change
Content-Type: application/sdp
Content-Length: 246

v=0
o=root 889042071 889042072 IN IP4 192.168.100.53
s=call
c=IN IP4 192.168.100.53
t=0 0
m=audio 50744 RTP/AVP 0 8 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv
Received from udp:192.168.100.200:17694 at Jan 2 05:06:05 (301 bytes):

ACK sip:192.168.100.53:5060 SIP/2.0
Via: SIP/2.0/UDP 172.22.17.11;rport;branch=z9hG4bK9XB6mgpSeQevK
Max-Forwards: 70
From: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
To: <sip:192.168.100.53>;tag=ey1s5tnvyz
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 131758205 ACK
Content-Length: 0

Received from udp:192.168.100.200:17694 at Jan 2 05:06:05 (351 bytes):

INFO sip:192.168.100.53:5060 SIP/2.0
Via: SIP/2.0/UDP 172.22.17.11;rport;branch=z9hG4bKcSQgt1835HHmp
Max-Forwards: 70
From: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
To: <sip:192.168.100.53>;tag=ey1s5tnvyz
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 131758206 INFO
Content-Length: 0
Contact: <sip:172.22.17.11:5060;transport=udp>

Sent to udp:192.168.100.200:17694 at Jan 2 05:06:05 (360 bytes):

SIP/2.0 200 Ok
Via: SIP/2.0/UDP 172.22.17.11;rport=17694;branch=z9hG4bKcSQgt1835HHmp;received=192.168.100.200
From: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
To: <sip:192.168.100.53>;tag=ey1s5tnvyz
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 131758206 INFO
User-Agent: snom320/8.7.5.35
Contact: <sip:192.168.100.53:5060>
Content-Length: 0

Sent to udp:172.22.17.11:5060 at Jan 2 05:06:07 (502 bytes):

BYE sip:172.22.17.11:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.100.53:5060;branch=z9hG4bK-z500ebvfq9zc;rport
From: <sip:192.168.100.53>;tag=ey1s5tnvyz
To: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 1 BYE
Max-Forwards: 70
User-Agent: snom320/8.7.5.35
Contact: <sip:192.168.100.53:5060>
RTP-RxStat: Total_Rx_Pkts=62,Rx_Pkts=62,Rx_Pkts_Lost=0,Remote_Rx_Pkts_Lost=0
RTP-TxStat: Total_Tx_Pkts=110,Tx_Pkts=110,Remote_Tx_Pkts=0
Content-Length: 0

Sent to udp:172.22.17.11:5060 at Jan 2 05:06:08 (502 bytes):

BYE sip:172.22.17.11:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.100.53:5060;branch=z9hG4bK-z500ebvfq9zc;rport
From: <sip:192.168.100.53>;tag=ey1s5tnvyz
To: <sip:anonym@172.22.17.11>;tag=0KD795Sv0tS4D
Call-ID: 07ae52d5-74c5-1237-eebd-3ac0b2717a22
CSeq: 1 BYE
Max-Forwards: 70
User-Agent: snom320/8.7.5.35
Contact: <sip:192.168.100.53:5060>
RTP-RxStat: Total_Rx_Pkts=62,Rx_Pkts=62,Rx_Pkts_Lost=0,Remote_Rx_Pkts_Lost=0
RTP-TxStat: Total_Tx_Pkts=110,Tx_Pkts=110,Remote_Tx_Pkts=0
Content-Length: 0
```

**Comment by haeferer** [comment]
> responses - yes. But the BYE is a request, and should be sent the address in the Contact header.
> 
> I need more clarity on this -- the call is successfully set up, and then which side sends the BYE?
> 
> Can you remove all of your code that is setting the Contact etc. and just show me a full drachtio log starting with the INVITE and ending with the failed BYE.

Yup, wait a second

**Comment by davehorton** [comment]
ok, so it is a double-nat situation.  The drachtio server is *not* at a public IP address, but is on a network behind its own NAT.  Note that this is a different situation than when you send a call to your carrier, which is at a public address.

Is this correct?

**Comment by haeferer** [comment]
Yep, the DrachtIO Server has no Public Address, not for the phone, not for the carrier !
So for me there is no difference between 

carrier : is reachable by an IP, but can not directly call the DrachtServer

phone: is reachable by an IP, but can not directly call the DrachtServer

Out carrier works without an external IP (at least for the BYE to an established call)

**Comment by haeferer** [comment]
If this works, we also try to uses the same way for Incoming Calls (from the carrier). This works perfect with a SoftPhone (phonerlite) as long as the Phone RESubScribe from time to time. Incoming Invites will be send to the Port and IP from the Last Subscribe

**Comment by davehorton** [comment]
I'm not completely following, but I am sure your carrier provides a public IP to which you send INVITEs in order to connect them.  If you hosted the drachtio server at a public address, then it would be more of an apples to apples comparison.

double-nat scenarios are difficult.  In production you would typically see SBCs deployed to resolve these. Given that your phones are behind a nat, why are you not simply putting the drachtio server on a hosted service (google, aws, digital ocean, etc) with a public address?

Here is what a typical VoIP scenario looks like, which the drachtio server would handle perfectly:
1.  Phones are behind a nat
2.  Drachtio server is at a public address
3.  Phones register and send INVITEs to drachtio server at public address
4.  drachtio server detects the phone is behind a nat, and will send responses and requests to the originating IP, even if different from the contact
5.  Phones re-REGISTER every 30 seconds or so to keep the pinhole open on the nat

I'd suggest trying to fit into that setup

**Comment by haeferer** [comment]
Ok, we will try this.

Many thx for your patience and the great support

By the way, is there a way to manipulate the contact header? (Just to try this solution)




Von meinem iPhone gesendet

Am 07.12.2018 um 14:43 schrieb Dave Horton <notifications@github.com<mailto:notifications@github.com>>:


I'm not completely following, but I am sure your carrier provides a public IP to which you send INVITEs in order to connect them. If you hosted the drachtio server at a public address, then it would be more of an apples to apples comparison.

double-nat scenarios are difficult. In production you would typically see SBCs deployed to resolve these. Given that your phones are behind a nat, why are you not simply putting the drachtio server on a hosted service (google, aws, digital ocean, etc) with a public address?

Here is what a typical VoIP scenario looks like, which the drachtio server would handle perfectly:

  1.  Phones are behind a nat
  2.  Drachtio server is at a public address
  3.  Phones register and send INVITEs to drachtio server at public address
  4.  drachtio server detects the phone is behind a nat, and will send responses and requests to the originating IP, even if different from the contact
  5.  Phones re-REGISTER every 30 seconds or so to keep the pinhole open on the nat

I'd suggest trying to fit into that setup

**Comment by davehorton** [comment]
you can set a contact header, as you were doing, but the host part will be re-written to be the ip address (or the public ip address, if the configured contact header has an "external-ip" attribute) of the network interface the request is going out on.

In any case, I am not sure what value sending an INFO message would have had....that will have no affect on where the subsequent BYE is sent.  The BYE will always be sent to the Contact header in the original INVITE by the phone.

I do a lot of work with VoIP carriers and there are standard ways for addressing these nat issues, mainly what I outlined above, and I'd suggest trying to stick to those patterns

**Comment by haeferer** [comment]
Understood.

Thx



Von meinem iPhone gesendet

Am 07.12.2018 um 14:53 schrieb Dave Horton <notifications@github.com<mailto:notifications@github.com>>:


you can set a contact header, as you were doing, but the host part will be re-written to be the ip address (or the public ip address, if the configured contact header has an "external-ip" attribute) of the network interface the request is going out on.

In any case, I am not sure what value sending an INFO message would have had....that will have no affect on where the subsequent BYE is sent. The BYE will always be sent to the Contact header in the original INVITE by the phone.

I do a lot of work with VoIP carriers and there are standard ways for addressing these nat issues, mainly what I outlined above, and I'd suggest trying to stick to those patterns
