### ISSUE TITLE
Handling ISUP Messages

### ISSUE THREAD

**Issue by haeferer** [davehorton/drachtio-server#67]
Hi, 

Does DrachtIO server is able to handle ISUP Messages over SIP (as defined in RFC https://www.rfc-editor.org/rfc/rfc3372.txt) to receive PSTN call informations from PSTN Gateways.

It seems (if the gateway supports this behaviour) the ISUP Message should be transported within a Multipart body?

**Comment by davehorton** [comment]
I've not done any work to support that specific RFC, or ISUP interop in general.  However, drachtio does provide some support for multipart bodies.  In the incoming invite request, the `req.payload` property will be an array of the part contents, as discussed here: https://drachtio.org/api#message-prop-payload

**Comment by davehorton** [comment]
I'd be interested to know more about the scenarios / networks in which you find ISUP over SIP still a thing, as the spec is quite old and I'd figured the air had gone out of that balloon as we slowly are becoming an all-VoIP world.

**Comment by haeferer** [comment]
We are working in a telecom environment using  outbound calls but a significant amount of PSTN ( ISDN ) on the other side (especiAlly Hardware Gateways SIP -> ISDN).
For scenarios like „temporary not available“ gateway send ISUP messages long before the final Sip Response (Gateway Plays an Audio Stream saying „not available“ and the ends the call). Our system can cancel the call in this scenarios earlier.



Von meinem iPhone gesendet

Am 19.12.2018 um 16:16 schrieb Dave Horton <notifications@github.com<mailto:notifications@github.com>>:


I'd be interested to know more about the scenarios / networks in which you find ISUP over SIP still a thing, as the spec is quite old and I'd figured the air had gone out of that balloon as we slowly are becoming an all-VoIP world.

**Comment by davehorton** [comment]
Ah, interesting, thanks for the elucidation.  Let me know if you are able to do what you need through examining the multipart content, or if more support is needed somewhere.

**Comment by haeferer** [comment]
Yup, we will try this

You may close this issue

Von meinem iPhone gesendet

Am 19.12.2018 um 17:03 schrieb Dave Horton <notifications@github.com<mailto:notifications@github.com>>:


Ah, interesting, thanks for the elucidation. Let me know if you are able to do what you need through examining the multipart content, or if more support is needed somewhere.
