### ISSUE TITLE
Active sessions stats

### ISSUE THREAD

**Issue by garnatha** [davehorton/drachtio-server#70]
I'm looking for a stat that represents the number of active sessions Drachtio currently has in-flight but I do not see anything in the existing watchdog dump to reflect this nor can I see a way to calculate this from the existing data. This seems to be the case for both server and apps. 

Would it be possible to expose Sofia stats? Or is there another way one could produce a metric to reflect how many sessions the server "thinks" are still active? 

Thanks!

**Comment by davehorton** [comment]
I've been looking at statsd and / or Prometheus integration as a possibility for this

**Comment by davehorton** [comment]
created the 'prometheus-support' branch for this work to enable scraping of monitoring stats by prometheus.io

**Comment by davehorton** [comment]
Closing as this is now available on the develop branch via support for prometheus metrics scraping
