### ISSUE TITLE
Crash happens when using proxyRequest

### ISSUE THREAD

**Issue by CelsoGalo** [davehorton/drachtio-server#73]
Hello Dave! I hope you are fine!

I am facing a crash when using proxyRequest. My code is pretty simple:
```
            srf.invite((req, res) => {
                logger.info('INVITE has been received');
                srf.proxyRequest(req, '192.168.7.14:5060', {
                    provisionalTimeout: '2s'
                });
            });
```
I compiled drachtio-server with debugging support, so I get the following assert printed in the shell before crashing:
**drachtio: ../src/sip-proxy-controller.cpp:549: bool drachtio::ProxyCore::ClientTransaction::forwardRequest(msg_t*, const string&): Assertion `p' failed.**
-->> This is related to the following assert:
```
        string record_route, transport;
        std::shared_ptr<SipTransport> p = SipTransport::findAppropriateTransport(m_target.c_str());
        assert(p) ;
```

Logs from Drachtio Server are attached. I think this is related to the "no transports found" mentioned in the logs. I tried to do workaround in many ways without success.

Thank you so much for helping.
[drachtio-msrp-relay.log](https://github.com/davehorton/drachtio-server/files/3063707/drachtio-msrp-relay.log)

**Comment by davehorton** [comment]
thx, will look into this...

what version/build are you running?  For some reason the log line that shows the build version is incomplete.  Can you verify this occurs with a build from the head of the develop branch, or latest docker image?

**Comment by davehorton** [comment]
also could you try this and let me know the results (with log)
```
srf.proxyRequest(req, '192.168.7.14:5060;transport=tcp'
```

**Comment by CelsoGalo** [comment]
Thanks Dave for the quick reply!

I am using the latest from develop branch. I cloned again the repository yesterday and built again from scratch.

I set now the 'transport=tcp' in the end as you requested, result is the same:
2019-04-10 10:31:50.464686 isLocalSipUri: checking to see if this is one of mine: sip:3000@DummyTarget.com;transport=tcp
2019-04-10 10:31:50.464721 SipTransport::findAppropriateTransport: searching for a transport to reach udp/sip:192.168.7.14:5060;transport=tcp
2019-04-10 10:31:50.465990 SipTransport::findAppropriateTransport: host parsed as 192.168.7.14
2019-04-10 10:31:50.466020 SipTransport::findAppropriateTransport - after filtering for transport we have 1 candidates
2019-04-10 10:31:50.466043 SipTransport::findAppropriateTransport - after filtering for protocol we have 0 candidates
2019-04-10 10:31:50.466076 SipTransport::findAppropriateTransport: - no transports found

**Comment by davehorton** [comment]
ok, thanks.  I think I have enough info to recreate myself.  Will update once I have results

**Comment by davehorton** [comment]
OK, I have made a fix on the 'prometheus-support' branch.  Are you able to build and test that branch?  If you have been using a docker image, let me know and I can build you a custom image for testing.

This build should work with either of the approaches you tried previously:
- if you provide a destination with an explicit transport, e.g. `sip: 192.168.7.14:5060;transport=tcp`
- with no explicit transport, e.g `sip:192.168.7.14:5060`

Note: please do provide the destination as a full sip uri, i.e. with the "sip:" prefix.

It would actually be great if you could verify that both of those work in your scenario.

**Comment by CelsoGalo** [comment]
Thank you so much, Dave!
I am trying to clone properly that repository... Still having problems because of submodule deps/prometheus-cpp, as it has a git URL and not https. As the others all use https, can you maybe change it? From inside the company I can only use https. But anyway I am still trying to fix by myself here :-), but suffering a bit as I am not familiar with git submodules.

**Comment by davehorton** [comment]
ah yes, good point.  will do...wait one

**Comment by davehorton** [comment]
ok, try now.

**Comment by CelsoGalo** [comment]
I fetched your change, thanks! But somehow I still have problems:
# git submodule update --init --recursive
fatal: Needed a single revision
Unable to find current revision in submodule path 'deps/prometheus-cpp'

**Comment by davehorton** [comment]
can you try checking the project out into a fresh directory and building?

**Comment by davehorton** [comment]
any luck with this?  I was able to build on a fresh server (and travis built as well) so I think the error is an artifact of the earlier checkout you did.

**Comment by CelsoGalo** [comment]
Sorry, retrying now on a fresh repository. So far so good.

**Comment by CelsoGalo** [comment]
Now I got everything fress... Everything was fine up to this point: make fails:

make[2]: Leaving directory '/root/git-repos-1/drachtio-server/deps/prometheus-cpp/build'
g++ -std=c++17  -g -O2 -L/usr/local/lib -L../deps/prometheus-cpp/build/deploy/usr/local/lib -L../deps/boost_1_69_0/stage/lib  -o drachtio src/drachtio-main.o src/drachtio-controller.o src/drachtio-drachtio-config.o src/drachtio-client-controller.o src/drachtio-client.o src/drachtio-drachtio.o src/drachtio-sip-dialog.o src/drachtio-sip-dialog-controller.o src/drachtio-sip-proxy-controller.o src/drachtio-pending-request-controller.o src/drachtio-timer-queue.o src/drachtio-cdr.o src/drachtio-timer-queue-manager.o src/drachtio-sip-transports.o src/drachtio-request-handler.o src/drachtio-request-router.o src/drachtio-stats-collector.o ../deps/sofia-sip/libsofia-sip-ua/.libs/libsofia-sip-ua.a ../deps/jansson-2.10/src/.libs/libjansson.a -lcurl -lpthread -lssl -lcrypto -lz ../deps/boost_1_69_0/stage/lib/libboost_thread.a ../deps/boost_1_69_0/stage/lib/libboost_system.a ../deps/boost_1_69_0/stage/lib/libboost_log.a ../deps/boost_1_69_0/stage/lib/libboost_filesystem.a ../deps/prometheus-cpp/build/deploy/usr/local/lib/libprometheus-cpp-pull.a ../deps/prometheus-cpp/build/deploy/usr/local/lib/libprometheus-cpp-core.a -lpthread -lssl -lcrypto -lz -lrt  
g++: error: ../deps/prometheus-cpp/build/deploy/usr/local/lib/libprometheus-cpp-pull.a: No such file or directory
g++: error: ../deps/prometheus-cpp/build/deploy/usr/local/lib/libprometheus-cpp-core.a: No such file or directory
Makefile:581: recipe for target 'drachtio' failed
make[1]: *** [drachtio] Error 1
make[1]: Leaving directory '/root/git-repos-1/drachtio-server/build'
Makefile:445: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CelsoGalo** [comment]
It seems the library were produced on another (lib64) folder:
The error:
g++: error: ../deps/prometheus-cpp/build/deploy/usr/local/**lib**/libprometheus-cpp-pull.a: No such file or directory
g++: error: ../deps/prometheus-cpp/build/deploy/usr/local/**lib**/libprometheus-cpp-core.a: No such file or directory

Locating the libraries:
\# find . -name libprometheus-cpp-pull.a
./deps/prometheus-cpp/build/deploy/usr/local/**lib64**/libprometheus-cpp-pull.a
./deps/prometheus-cpp/build/pull/libprometheus-cpp-pull.a

\# find . -name libprometheus-cpp-core.a
./deps/prometheus-cpp/build/core/libprometheus-cpp-core.a
./deps/prometheus-cpp/build/deploy/usr/local/**lib64**/libprometheus-cpp-core.a

**Comment by davehorton** [comment]
that’s interesting, what distro are you building on?

On Apr 11, 2019, at 4:53 PM, Celso Sidor <notifications@github.com> wrote:

It seems the library were produced on another (lib64) folder:
The error:
g++: error: ../deps/prometheus-cpp/build/deploy/usr/local/lib/libprometheus-cpp-pull.a: No such file or directory
g++: error: ../deps/prometheus-cpp/build/deploy/usr/local/lib/libprometheus-cpp-core.a: No such file or directory

Locating the libraries:
# find . -name libprometheus-cpp-pull.a
./deps/prometheus-cpp/build/deploy/usr/local/lib64/libprometheus-cpp-pull.a
./deps/prometheus-cpp/build/pull/libprometheus-cpp-pull.a

# find . -name libprometheus-cpp-core.a
./deps/prometheus-cpp/build/core/libprometheus-cpp-core.a
./deps/prometheus-cpp/build/deploy/usr/local/lib64/libprometheus-cpp-core.a

**Comment by CelsoGalo** [comment]
openSUSE 42.3 (x86_64) is our platform.

**Comment by CelsoGalo** [comment]
Sorry, I just created a link from lib to lib64 folder. Going on...

**Comment by CelsoGalo** [comment]
Hi Dave, good news, both cases work fine (with or without explicit transport indication).
Thank you so much!!

**Comment by CelsoGalo** [comment]
Last question Dave :-). From now one I would need to use this branch? Thanks again!

**Comment by davehorton** [comment]
I plan on merging this branch into the develop branch within the next week.  I'll try to sort out this build issue before then as well.  Leaving open for now, will close once I merge into develop

**Comment by CelsoGalo** [comment]
Alright, thank you so much!!

**Comment by davehorton** [comment]
I think I have sorted the build problem.  Could you try a fresh checkout on that branch and see if it builds for you now?
