### ISSUE TITLE
Server crashes after client sends reinvite

### ISSUE THREAD

**Issue by benlai2018** [davehorton/drachtio-server#76]
Hi Dave,

My use case is running drachtio server with drachtio-siprec-recording to record calls. I use dialog.modify(sdp) to pause and resume the recording. The cause is that orq is used in both RIP and IIP, so it is double destroyed in clearRIP and clearIIP.

I have sent to your email box the logs as well as a possible patch. 

Thanks

Ben Lai

**Comment by davehorton** [comment]
can you share a drachtio log for this?  Preferably showing the startup of the drachtio server, followed by the invite and re-INVITE

**Comment by davehorton** [comment]
Just to be clear, are you using the 'develop' branch?  I made a quick test against that branch and for some reason I cannot recreate..

**Comment by davehorton** [comment]
also, if you can report the version you are using by running `drachtio --version` and providing the result that would be most useful

**Comment by benlai2018** [comment]
Yes, develop branch

**Comment by davehorton** [comment]
It looks like your scenario has more than just a reINVITE.  I see the app send the INVITE as a uac, then send a reINVITE, and then 3 seconds, later (just before the end of the log) it looks like it is going to send another reINVITE.  Is that accurate?  I need to create a simple test app that mimics this

**Comment by benlai2018** [comment]
I sent several "dialog.modify(sdp)" in client, to toggle pause/resume the recording. I only change one attribute in sdp(toggle "a=inactive" and "a=recvonly"), nothing else changed for each request

**Comment by davehorton** [comment]
I don't think I am seeing your entire log.  Can you send me a full drachtio.log file, unredacted, starting with startup ?  You can email it to me.

I've tried a test app that establishes a UAC dialog and then does 3 reINVITEs and that does not crash.

Also the log snippet you sent me ends with receving a message from the app:

```
2019-04-28 05:31:41.983583 Client::read_handler read: 3e79532e-0cec-4751-8f19-c27ba26537ca|sip||364D2870-5CC53AB3000A8D8C-D59F5700;uas
INVITE sip:placeholder SIP/2.0
Contact: <sip:10.131.10.26:5060;transport=tcp>
Content-Length: 309
 
v=0
o=- 1388723062 1879454526 IN IP4 10.141.12.13
s=-
c=IN IP4 10.141.12.13
t=0 0
m=audio 35694 RTP/AVP 0
c=IN IP4 10.141.12.13
a=rtpmap:0 PCMU/8000
a=rtcp:35695
a=recvonly
a=label:a_leg
m=audio 35710 RTP/AVP 0
c=IN IP4 10.141.12.13
a=rtpmap:0 PCMU/8000
a=rtcp:35711
a=recvonly
a=label:b_leg
```
Its kind of strange if it crashed there, without further logging, so I am guessing some logging is missing.

Finally, if you have time, could you see if you are able to recreate this on the 'memory-debug' branch?  I have reworked and simplified the timerD handling on that branch which is related to what is going on.  I'm going to be merging that into the develop branch shortly and it would be good to know if you also see the problem on that branch.

Sorry for all the requests, but in order to fix I first need to add a test case that fails with the current develop branch and so far I have not been able to do that

**Comment by benlai2018** [comment]
I'll create a completed log file and send it to you.

**Comment by davehorton** [comment]
thanks, also please have sofia-loglevel at 9 and loglevel 'debug'

**Comment by benlai2018** [comment]
I sent two logs with stack trace by email. they were running with "--loglevel debug --sofia-loglevel 9"

**Comment by davehorton** [comment]
thanks that is very useful.  The two logs crashed in two different places, which is interesting.  Is it still the case that with your patch you can not recreate this crash?  Also, can you possibly test your scenario with the memory-debug branch and see if you can get that to crash in the same way?
Meanwhile I will work on recreating myself.

**Comment by davehorton** [comment]
I was able to recreate, and I believe I have fixed.  Can you build the latest from the 'develop' branch and re-run your tests?

**Comment by benlai2018** [comment]
Yes, with the patch, the crash does not happen no matter how many reinvites I send from client.
I'm trying to build latest memory-debug, and will post here any update.

**Comment by davehorton** [comment]
ok, actually if you can build the latest from the develop branch to test that (just checked in a fix ~10 mins ago), that would be great

**Comment by benlai2018** [comment]
memory-debug branch crashes too. I have sent you another log file for this branch. I will test you latest code in develop.

**Comment by benlai2018** [comment]
I think the latest fix (149f66a) will work, as I tried to comment out the following line in clearFinalIIP before and it worked. Actually this line is where the second one of double destroys happens.
       if( orq ) nta_outgoing_destroy( orq ) ;
I will post the final test result.

**Comment by benlai2018** [comment]
This fix(149f66a) works. No crash anymore in test. Thanks Dave.

**Comment by davehorton** [comment]
many thanks for your help on this one.  Much appreciated!

**Comment by benlai2018** [comment]
Hi Dave,

This change in v0.8.3-rc3 reverted the fix in v0.8.1-rc3 for this issue. Could you please have a look?

@@ -1689,7 +1694,7 @@ namespace drachtio {
         m_mapTransactionId2IIP.erase( itTransaction ) ;
 
         if( irq ) nta_incoming_destroy( irq ) ;
-        //if( orq ) nta_outgoing_destroy( orq ) ;
+        if( orq ) nta_outgoing_destroy( orq ) ;

**Comment by davehorton** [comment]
oh darn, my bad.  Will take a look.  This was part of fixing some memory leaks, and it looks like I took too heavy a hand...

**Comment by davehorton** [comment]
just pushed v0.8.4-rc1 that comments this line out.  Can you retest and verify it no longer crashes?

Meanwhile, I will investigate a proper fix that addresses the memory leak
