### ISSUE TITLE
CDRs do not seem to be firing properly

### ISSUE THREAD

**Issue by TimMeade** [davehorton/drachtio-server#79]
I'm very new to drachtio but long time telecom developer.    I'm going through the code bases and it appears to me that something is odd with the CDRs firing.  Most likely a misunderstanding on my part, but here is what i see;

Note:  This is the latest docker image as of time/date of this posting.  I do have <cdrs>true</cdrs> in the drachtio.conf.xml and verfied it by exec into the running docker image.

When working with CDRs should all 3 'on' methods fire for a good call?  I'm doing a createB2BUA with an inbound call to an outbound B leg.    I have the following CDR app code:

```
const Srf = require('drachtio-srf');
const srf = new Srf();

srf.connect({
  host: '1.1.1.1',
  port: 9022,
  secret: 'password',
});

srf
  .on('connect', (err, hostport) => {
    console.log(`connected to a drachtio server listening on: ${hostport}`);
  })
  .on('error', err => {
    console.log(`Error connecting to drachtio server: ${err}`);
  });

// register to receive CDRs
srf.on('cdr:attempt', (source, time, msg) => {
  console.log(
    `got attempt record from ${source} at ${time}: ${msg.get('Call-Id')}`,
  );
});

srf.on('cdr:start', (source, time, role, msg) => {
  console.log(
    `got start record from ${source} at ${time} with role ${role}: ${msg.get(
      'Call-Id',
    )}`,
  );
});

srf.on('cdr:stop', (source, time, reason, msg) => {
  console.log(
    `got stop record from ${source} at ${time} with reason ${reason}: ${msg.get(
      'Call-Id',
    )}`,
  );
});
```
Note:  This connects fine, i changed server for security.

In the main app i have the createB2BUA section that works well with the calls . But the only section that i see in CDR is the attempt method.   No matter how long the call is up .  The attempt fires prior to the call setup.

I also have a "go away" section in the main app that only does: 

```   
console.log(`Hanging up on ${req.calledNumber}`);
    res.send(486, 'So sorry, busy right now', {
      headers: {
        'X-Custom-Header': 'because why not?',
      },
    });
```
This section is only if I don't recognize the source.    Here i have seen CDR code fire the start and stop.     

I would think the start and stop should fire for every call.  Most likely for every leg of every call.  But that does not seem to be the case.

So just a little confused.   

Thanks

Tim

**Comment by davehorton** [comment]
I'll check into it...my guess is that there is an issue with cdrs in the b2b scenario.  I originally implemented and tested this in the proxy scenario, and found recently I had neglected to implement them for b2b....I then thought I had fixed them, but apparently maybe not.  Will investigate further

**Comment by davehorton** [comment]
Yes, I see now I made some changes for this but never merged them.  Any chance that you can build and test against the 'b2b-cdr' branch so I can verify your tests work before I merge into develop?

**Comment by TimMeade** [comment]
Sure.    I’ll pull first thing in the morning.

**Comment by TimMeade** [comment]
Pulled and built the docker from the server branch.  Now seeing:

```
got attempt record from network at 12:31:03.010064: 369397877_48982852@207.11.11.11
got attempt record from application at 12:31:03.056861: 24e65e2d-f1b0-1237-dba2-0050568d51f2
got start record from network at 12:31:06.646269 with role uac: 24e65e2d-f1b0-1237-dba2-0050568d51f2
got start record from application at 12:31:06.691696 with role uas: 369397877_48982852@207.11.11.11
got stop record from network at 12:31:15.799471 with reason normal-release: 369397877_48982852@207.11.11.11
got stop record from application at 12:31:15.843260 with reason normal-release: 24e65e2d-f1b0-1237-dba2-0050568d51f2
```
I will need to test further but appears much better.

Thanks

**Comment by davehorton** [comment]
closing this as I have merged the changes into the develop branch, and the v0.8.2 release.  Please reopen if you come across any further related issues.
