### ISSUE TITLE
Offer/answer exchanged on 200OK + ACK seem not supported

### ISSUE THREAD

**Issue by CelsoGalo** [davehorton/drachtio-server#84]
Hello Dave! We have scenarios that our SIP servers send offerless INVITES, expecting the SDPs to be exchanged ahead at 200OK and ACK. I tried to use Drachtio in this case, but it seems it is not supported (maybe it is but not explicitly documented?).

Currently I am using createUAC() and createUAS() for handling it at both sides. I can indeed send offerless INVITEs from my UAC Drachtio and have them received at the UAS Drachtio and also  can answer the 200OK with the offer SDP. But it happens something strange in the UAC Drachtio, it answers back with the same SDP in the ACK with is the same received but with zeroed IPs in the o= line and in the t= line. What is need is to fully control the SDPs being generated at all places (INVITE, SDP and also ACK), not only during initial handling, but also during re-INVITES. It seems nowadays I do not have a way to handle SDPs for the ACK, not only at the sending side (UAC role) but also in the receiving one (UAS role).

Do you think we could have that implemented?

Thanks a lot and have a great weekend.

**Comment by davehorton** [comment]
some of this may work, but it is not well documented.

On the UAC side, try setting `opts.noAck` to true, ie.
```
srf.createUAC(uri, {noAck: true, ...}, ..
```
This is going to cause the method to resolve not with a SipDialog, but with an object containing the remote SDP offered in the 200 OK by the remote side, and an 'ack' function that you must call, passing your own SDP.  And that function, when called, then resolves into your dialog.

Whew...that's a bit complicated!  (sorry).

So then, something like this:
```
const {sdp, ack}= await createUAC(uri, {noAck: true});
// sdp = the remote sdp; ack is a function..

// now allocate your local sdp, by whatever means..
const uac = await ack(localSdp);
```

**Comment by davehorton** [comment]
were you able to try this out?

https://drachtio.org/docs#sending-a-3pcc-invite

**Comment by CelsoGalo** [comment]
Hi Dave. Yes, that worked fine to me, thanks!
