### ISSUE TITLE
View running calls

### ISSUE THREAD

**Issue by WhiteyDude** [davehorton/drachtio-server#88]
Hi Dave,

Is there a way to see what calls are currently active on drachtio? Either via a JS application or from console, or even from a memory/local DB that can be called.

I've noticed during dev I've restarted my application a lot of times which has left unclean calls still running in the background, as I never tore them down. It would be very handy to be able to pull a list of "active" calls from drachtio.

Thanks!

**Comment by davehorton** [comment]
every 30 seconds the logs will show a bunch of stats including active dialogs.  Integration with prometheus.io can also be used to monitor this data in prometheus.
